// <auto-generated>
//   本文件由 tools/udfgen.py 从 udf-metadata/ArrayUdf.json 生成——请勿手工修改。
//   改函数名/描述/参数/分类 → 改元数据后运行：
//       python tools/udfgen.py generate
//   改实现逻辑 → 改 Core 层，或在元数据的 expr 中调整调用。
//   元数据与生成物的一致性由 scripts/verify-udfgen.ps1 门禁强制。
// </auto-generated>
// CS8669：带 // <auto-generated> 的文件中，可空引用批注要求显式 #nullable 指令。
#nullable enable
using ExcelDna.Integration;
using ExcelFormulaLabs.Foundation;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ExcelFormulaLabs.DataToolkit
{
    public static partial class ArrayUdf
    {
        [ExcelFunction(Name = "ARR.SORT", Description = "Sort array. asc=true/false, mode=auto/text/numeric", Category = "Array")] public static object UDF_ARR_SORT([ExcelArgument(Name = "array", Description = "A range or 2D array")] object a, [ExcelArgument(Name = "[sort_order]", Description = "TRUE for ascending (default), FALSE for descending")] object asc=null, [ExcelArgument(Name = "[sort_mode]", Description = "Sort mode: auto (default), text, or numeric")] object mode=null)
            => OutputWrapper.WrapError(() => ArrayCore.Sort(A(a),InputNormalizer.ToBool(asc, true),ParseSortMode(mode)));

        [ExcelFunction(Name = "ARR.SORTASC", Description = "Sort array ascending (auto-detect type)", Category = "Array")] public static object UDF_ARR_SORTASC([ExcelArgument(Name = "array", Description = "A range or 2D array")] object a)
            => OutputWrapper.WrapError(() => ArrayCore.Sort(A(a),true,ComparerMode.Auto));

        [ExcelFunction(Name = "ARR.SORTDESC", Description = "Sort array descending (auto-detect type)", Category = "Array")] public static object UDF_ARR_SORTDESC([ExcelArgument(Name = "array", Description = "A range or 2D array")] object a)
            => OutputWrapper.WrapError(() => ArrayCore.Sort(A(a),false,ComparerMode.Auto));

        [ExcelFunction(Name = "ARR.SORTNUM", Description = "Sort array ascending by numeric value", Category = "Array")] public static object UDF_ARR_SORTNUM([ExcelArgument(Name = "array", Description = "A range or 2D array")] object a)
            => OutputWrapper.WrapError(() => ArrayCore.Sort(A(a),true,ComparerMode.Numeric));

        [ExcelFunction(Name = "ARR.SORTTEXT", Description = "Sort array ascending by text (case-insensitive)", Category = "Array")] public static object UDF_ARR_SORTTEXT([ExcelArgument(Name = "array", Description = "A range or 2D array")] object a)
            => OutputWrapper.WrapError(() => ArrayCore.Sort(A(a),true,ComparerMode.Text));

        [ExcelFunction(Name = "ARR.UNIQUE", Description = "Return unique values from an array", Category = "Array")] public static object UDF_ARR_UNIQUE([ExcelArgument(Name = "array", Description = "A range or 2D array")] object a)
            => OutputWrapper.WrapError(() => ArrayCore.Unique(A(a)));

        [ExcelFunction(Name = "ARR.INDEXOF", Description = "Zero-based index of first occurrence, or -1 if not found", Category = "Array")] public static object UDF_ARR_INDEXOF([ExcelArgument(Name = "array", Description = "A range or 2D array")] object a, [ExcelArgument(Name = "lookup_value", Description = "The value to search for in the array")] object v)
            => OutputWrapper.WrapError(() => (long)ArrayCore.IndexOf(A(a),v));

        [ExcelFunction(Name = "ARR.SLICE", Description = "Extract l elements from an array starting at index s", Category = "Array")] public static object UDF_ARR_SLICE([ExcelArgument(Name = "array", Description = "A range or 2D array")] object a, [ExcelArgument(Name = "start_index", Description = "Starting index, 0-based")] object s, [ExcelArgument(Name = "num_elements", Description = "Number of elements to extract")] object l)
            => OutputWrapper.WrapError(() => ArrayCore.Slice(A(a),InputNormalizer.ToLong(s),InputNormalizer.ToLong(l)));

        [ExcelFunction(Name = "ARR.FLATTEN", Description = "Flatten a 2D range into 1D, row-major order", Category = "Array")] public static object UDF_ARR_FLATTEN([ExcelArgument(Name = "array", Description = "A range or 2D array")] object a)
            => OutputWrapper.WrapError(() => ArrayCore.Flatten2D(InputNormalizer.NormalizeTo2D(a)!));

        [ExcelFunction(Name = "ARR.FILTER", Description = "Filter array by comparison operator: =, <>, >, <, >=, <=", Category = "Array")] public static object UDF_ARR_FILTER([ExcelArgument(Name = "array", Description = "A range or 2D array")] object a, [ExcelArgument(Name = "criteria", Description = "The criteria value to compare each element against")] object c, [ExcelArgument(Name = "comparison_operator", Description = "Comparison operator: =, <>, >, <, >=, or <=")] object op)
            => OutputWrapper.WrapError(() => {using (RegexBudget.Begin()) return ArrayCore.Filter(A(a),c,InputNormalizer.ToString(op));});

        [ExcelFunction(Name = "ARR.FILTER_EQ", Description = "Filter array for elements equal to c", Category = "Array")] public static object UDF_ARR_FEQ([ExcelArgument(Name = "array", Description = "A range or 2D array")] object a, [ExcelArgument(Name = "criteria", Description = "The criteria value to compare each element against")] object c)
            => OutputWrapper.WrapError(() => ArrayCore.Filter(A(a),c,"="));

        [ExcelFunction(Name = "ARR.FILTER_NE", Description = "Filter array for elements not equal to c", Category = "Array")] public static object UDF_ARR_FNE([ExcelArgument(Name = "array", Description = "A range or 2D array")] object a, [ExcelArgument(Name = "criteria", Description = "The criteria value to compare each element against")] object c)
            => OutputWrapper.WrapError(() => ArrayCore.Filter(A(a),c,"<>"));

        [ExcelFunction(Name = "ARR.FILTER_GT", Description = "Filter array for elements greater than c", Category = "Array")] public static object UDF_ARR_FGT([ExcelArgument(Name = "array", Description = "A range or 2D array")] object a, [ExcelArgument(Name = "criteria", Description = "The criteria value to compare each element against")] object c)
            => OutputWrapper.WrapError(() => ArrayCore.Filter(A(a),c,">"));

        [ExcelFunction(Name = "ARR.FILTER_LT", Description = "Filter array for elements less than c", Category = "Array")] public static object UDF_ARR_FLT([ExcelArgument(Name = "array", Description = "A range or 2D array")] object a, [ExcelArgument(Name = "criteria", Description = "The criteria value to compare each element against")] object c)
            => OutputWrapper.WrapError(() => ArrayCore.Filter(A(a),c,"<"));

        [ExcelFunction(Name = "ARR.CONCAT", Description = "Concatenate two arrays", Category = "Array")] public static object UDF_ARR_CONCAT([ExcelArgument(Name = "array1", Description = "First range or array")] object a, [ExcelArgument(Name = "array2", Description = "Second range or array")] object b)
            => OutputWrapper.WrapError(() => ArrayCore.Concat(A(a),A(b)));

        [ExcelFunction(Name = "ARR.REVERSE", Description = "Reverse array order", Category = "Array")] public static object UDF_ARR_REVERSE([ExcelArgument(Name = "array", Description = "A range or 2D array")] object a)
            => OutputWrapper.WrapError(() => ArrayCore.Reverse(A(a)));

        [ExcelFunction(Name = "ARR.COUNT", Description = "Count of elements in an array", Category = "Array")] public static object UDF_ARR_COUNT([ExcelArgument(Name = "array", Description = "A range or 2D array")] object a)
            => OutputWrapper.WrapError(() => (long)ArrayCore.Count(A(a)));

        [ExcelFunction(Name = "ARR.CONTAINS", Description = "Returns TRUE if value exists in array", Category = "Array")] public static object UDF_ARR_CONTAINS([ExcelArgument(Name = "array", Description = "A range or 2D array")] object a, [ExcelArgument(Name = "lookup_value", Description = "The value to search for in the array")] object v)
            => OutputWrapper.WrapError(() => (object)ArrayCore.Contains(A(a),v));

        [ExcelFunction(Name = "ARR.TOSET", Description = "Return unique values (alias for ARR.UNIQUE)", Category = "Array")] public static object UDF_ARR_TOSET([ExcelArgument(Name = "array", Description = "A range or 2D array")] object a)
            => OutputWrapper.WrapError(() => ArrayCore.Unique(A(a)));

        [ExcelFunction(Name = "ARR.FILL", Description = "Create array of length n filled with value v", Category = "Array")] public static object UDF_ARR_FILL([ExcelArgument(Name = "value", Description = "The value to fill or format")] object v, [ExcelArgument(Name = "count", Description = "Number of elements to generate or fill")] object n)
            => OutputWrapper.WrapError(() => ArrayCore.Fill(v,InputNormalizer.ToLong(n)));

        [ExcelFunction(Name = "ARR.RANGE", Description = "Generate numeric sequence from start to end by step. Negative step for descending.", Category = "Array")] public static object UDF_ARR_RANGE([ExcelArgument(Name = "start", Description = "Starting value of the sequence")] object s, [ExcelArgument(Name = "end", Description = "Ending value of the sequence")] object e, [ExcelArgument(Name = "step", Description = "Step size between consecutive values. Use negative step for descending sequences.")] object step)
            => OutputWrapper.WrapError(() => ArrayCore.Sequence(InputNormalizer.ToDouble(s),InputNormalizer.ToDouble(e),InputNormalizer.ToDouble(step)));

        [ExcelFunction(Name = "ARR.SHUFFLE", Description = "Randomly shuffle array elements (Fisher-Yates)", Category = "Array")] public static object UDF_ARR_SHUFFLE([ExcelArgument(Name = "array", Description = "A range or 2D array")] object a)
            => OutputWrapper.WrapError(() => ArrayCore.Shuffle(A(a)));

    }
}
