// <auto-generated>
//   本文件由 tools/udfgen.py 从 udf-metadata/DateTimeUdf.json 生成——请勿手工修改。
//   改函数名/描述/参数/分类 → 改元数据后运行：
//       python tools/udfgen.py generate
//   改实现逻辑 → 改 Core 层，或在元数据的 expr 中调整调用。
//   元数据与生成物的一致性由 scripts/verify-udfgen.ps1 门禁强制。
// </auto-generated>
// CS8669：带 // <auto-generated> 的文件中，可空引用批注要求显式 #nullable 指令。
#nullable enable
using ExcelDna.Integration;
using ExcelFormulaLabs.Foundation;
using System;

namespace ExcelFormulaLabs.DataToolkit
{
    public static partial class DateTimeUdf
    {
        [ExcelFunction(Name = "DT.ISOWEEK", Description = "ISO 8601 week number (1-53) from an Excel date", Category = "Date & Time")] public static object UDF_DT_ISOW([ExcelArgument(Name = "serial_number", Description = "An Excel date serial number")] object d)
            => OutputWrapper.WrapError(() => ElementWiseMapper.MapOver<double,long>(d,x=>DateTimeCore.IsoWeekNum(D(x))));

        [ExcelFunction(Name = "DT.WEEKDAY", Description = "Day of week as number (Sunday=1, Saturday=7, matches VBA Weekday)", Category = "Date & Time")] public static object UDF_DT_WKD([ExcelArgument(Name = "serial_number", Description = "An Excel date serial number")] object d)
            => OutputWrapper.WrapError(() => ElementWiseMapper.MapOver<double,long>(d,x=>DateTimeCore.Weekday(D(x))));

        [ExcelFunction(Name = "DT.WEEKDAYISO", Description = "Day of week as ISO number (Monday=1, Sunday=7)", Category = "Date & Time")] public static object UDF_DT_WKDISO([ExcelArgument(Name = "serial_number", Description = "An Excel date serial number")] object d)
            => OutputWrapper.WrapError(() => ElementWiseMapper.MapOver<double,long>(d,x=>DateTimeCore.WeekdayISO(D(x))));

        [ExcelFunction(Name = "DT.WEEKDAYNAME", Description = "English weekday name (e.g. 'Monday') from an Excel date", Category = "Date & Time")] public static object UDF_DT_WKDNAM([ExcelArgument(Name = "serial_number", Description = "An Excel date serial number")] object d)
            => OutputWrapper.WrapError(() => ElementWiseMapper.MapOver<double,string>(d,x=>DateTimeCore.WeekdayName(D(x))));

        [ExcelFunction(Name = "DT.SOW", Description = "Start of week date. sd = start day (0=Sun, 1=Mon, ...; default 1=Mon)", Category = "Date & Time")] public static object UDF_DT_SOW([ExcelArgument(Name = "serial_number", Description = "An Excel date serial number")] object d, [ExcelArgument(Name = "[start_day]", Description = "Day the week starts: 0=Sunday, 1=Monday (default)")] object sd=null)
            => OutputWrapper.WrapError(() => ElementWiseMapper.MapOver<double,double>(d,x=>DateTimeCore.StartOfWeek(D(x),SD(sd)).ToOADate()));

        [ExcelFunction(Name = "DT.EOW", Description = "End of week date. sd = start day (0=Sun, 1=Mon, ...; default 1=Mon)", Category = "Date & Time")] public static object UDF_DT_EOW([ExcelArgument(Name = "serial_number", Description = "An Excel date serial number")] object d, [ExcelArgument(Name = "[start_day]", Description = "Day the week starts: 0=Sunday, 1=Monday (default)")] object sd=null)
            => OutputWrapper.WrapError(() => ElementWiseMapper.MapOver<double,double>(d,x=>DateTimeCore.EndOfWeek(D(x),SD(sd)).ToOADate()));

        [ExcelFunction(Name = "DT.SOM", Description = "Start of month date (1st day of month)", Category = "Date & Time")] public static object UDF_DT_SOM([ExcelArgument(Name = "serial_number", Description = "An Excel date serial number")] object d)
            => OutputWrapper.WrapError(() => ElementWiseMapper.MapOver<double,double>(d,x=>DateTimeCore.StartOfMonth(D(x)).ToOADate()));

        [ExcelFunction(Name = "DT.EOM", Description = "End of month date (last day of month)", Category = "Date & Time")] public static object UDF_DT_EOM([ExcelArgument(Name = "serial_number", Description = "An Excel date serial number")] object d)
            => OutputWrapper.WrapError(() => ElementWiseMapper.MapOver<double,double>(d,x=>DateTimeCore.EndOfMonth(D(x)).ToOADate()));

        [ExcelFunction(Name = "DT.WOM", Description = "Week-of-month ordinal (1-6). sd = start day (0=Sun, ...; default 1=Mon)", Category = "Date & Time")] public static object UDF_DT_WOM([ExcelArgument(Name = "serial_number", Description = "An Excel date serial number")] object d, [ExcelArgument(Name = "[start_day]", Description = "Day the week starts: 0=Sunday, 1=Monday (default)")] object sd=null)
            => OutputWrapper.WrapError(() => ElementWiseMapper.MapOver<double,long>(d,x=>DateTimeCore.WeekOfMonth(D(x),SD(sd))));

        [ExcelFunction(Name = "DT.DIM", Description = "Days in month for given year and month", Category = "Date & Time")] public static object UDF_DT_DIM([ExcelArgument(Name = "year", Description = "A year number, e.g. 2024")] object y, [ExcelArgument(Name = "month", Description = "A month number between 1 and 12")] object m)
            => OutputWrapper.WrapError(() => (long)DateTimeCore.DaysInMonth(InputNormalizer.ToLong(y),InputNormalizer.ToLong(m)));

        [ExcelFunction(Name = "DT.AGEYEARS", Description = "Age in whole years from birth date to reference date (default: today)", Category = "Date & Time")] public static object UDF_DT_AGEY([ExcelArgument(Name = "start_date", Description = "Start date as Excel serial number")] object b, [ExcelArgument(Name = "[end_date]", Description = "End date as Excel serial number; default is today")] object r=null)
            => OutputWrapper.WrapError(() => (long)DateTimeCore.AgeYears(D(b),OptD(r)));

        [ExcelFunction(Name = "DT.AGEMONTHS", Description = "Age in whole months from birth date to reference date (default: today)", Category = "Date & Time")] public static object UDF_DT_AGEM([ExcelArgument(Name = "start_date", Description = "Start date as Excel serial number")] object b, [ExcelArgument(Name = "[end_date]", Description = "End date as Excel serial number; default is today")] object r=null)
            => OutputWrapper.WrapError(() => (long)DateTimeCore.AgeMonths(D(b),OptD(r)));

        [ExcelFunction(Name = "DT.AGEDAYS", Description = "Age in days from birth date to reference date (default: today)", Category = "Date & Time")] public static object UDF_DT_AGED([ExcelArgument(Name = "start_date", Description = "Start date as Excel serial number")] object b, [ExcelArgument(Name = "[end_date]", Description = "End date as Excel serial number; default is today")] object r=null)
            => OutputWrapper.WrapError(() => (long)DateTimeCore.AgeDays(D(b),OptD(r)));

        [ExcelFunction(Name = "DT.ISWE", Description = "Returns TRUE if date is Saturday or Sunday", Category = "Date & Time")] public static object UDF_DT_ISWE([ExcelArgument(Name = "serial_number", Description = "An Excel date serial number")] object d)
            => OutputWrapper.WrapError(() => ElementWiseMapper.MapOver<double,bool>(d,x=>DateTimeCore.IsWeekend(D(x))));

        [ExcelFunction(Name = "DT.ADDWKD", Description = "Add n workdays to a start date (Mon-Fri, skips weekends)", Category = "Date & Time")] public static object UDF_DT_AWKD([ExcelArgument(Name = "start_date", Description = "Start date as Excel serial number")] object s, [ExcelArgument(Name = "workdays", Description = "Number of workdays to add; negative to subtract")] object ds)
            => OutputWrapper.WrapError(() => DateTimeCore.AddWorkdays(D(s),InputNormalizer.ToLong(ds)).ToOADate());

        [ExcelFunction(Name = "DT.WKDBTWN", Description = "Count workdays (Mon-Fri) between two dates, exclusive of start", Category = "Date & Time")] public static object UDF_DT_WKDB([ExcelArgument(Name = "start_date", Description = "Start date as Excel serial number")] object s, [ExcelArgument(Name = "end_date", Description = "End date as Excel serial number (required)")] object e)
            => OutputWrapper.WrapError(() => (long)DateTimeCore.WorkdaysBetween(D(s),D(e)));

        [ExcelFunction(Name = "DT.NEXTWKD", Description = "Next workday on or after given date (skips weekends)", Category = "Date & Time")] public static object UDF_DT_NWKD([ExcelArgument(Name = "serial_number", Description = "An Excel date serial number")] object d)
            => OutputWrapper.WrapError(() => ElementWiseMapper.MapOver<double,double>(d,x=>DateTimeCore.NextWorkday(D(x)).ToOADate()));

        [ExcelFunction(Name = "DT.EASTER", Description = "Easter Sunday date for given year (Gregorian computus)", Category = "Date & Time")] public static object UDF_DT_EASTER([ExcelArgument(Name = "year", Description = "A year number, e.g. 2024")] object y)
            => OutputWrapper.WrapError(() => ElementWiseMapper.MapOver<long,double>(y,EasterOADate));

        [ExcelFunction(Name = "DT.QUARTER", Description = "Calendar quarter number (1-4) from date", Category = "Date & Time")] public static object UDF_DT_Q([ExcelArgument(Name = "serial_number", Description = "An Excel date serial number")] object d)
            => OutputWrapper.WrapError(() => ElementWiseMapper.MapOver<double,long>(d,x=>DateTimeCore.Quarter(D(x))));

        [ExcelFunction(Name = "DT.SEMESTER", Description = "Semester number (1 or 2) from date", Category = "Date & Time")] public static object UDF_DT_SEM([ExcelArgument(Name = "serial_number", Description = "An Excel date serial number")] object d)
            => OutputWrapper.WrapError(() => ElementWiseMapper.MapOver<double,long>(d,x=>DateTimeCore.Semester(D(x))));

        [ExcelFunction(Name = "DT.DOY", Description = "Day of year (1-366) from date", Category = "Date & Time")] public static object UDF_DT_DOY([ExcelArgument(Name = "serial_number", Description = "An Excel date serial number")] object d)
            => OutputWrapper.WrapError(() => ElementWiseMapper.MapOver<double,long>(d,x=>DateTimeCore.DayOfYear(D(x))));

        [ExcelFunction(Name = "DT.ISLEAP", Description = "Returns TRUE if year is a leap year", Category = "Date & Time")] public static object UDF_DT_ILEAP([ExcelArgument(Name = "year", Description = "A year number, e.g. 2024")] object y)
            => OutputWrapper.WrapError(() => ElementWiseMapper.MapOver<long,bool>(y,yr=>DateTimeCore.IsLeapYear(yr)));

        [ExcelFunction(Name = "DT.UNIXTS", Description = "Convert Excel date to Unix timestamp (seconds since 1970-01-01)", Category = "Date & Time")] public static object UDF_DT_UXTS([ExcelArgument(Name = "serial_number", Description = "An Excel date serial number")] object d)
            => OutputWrapper.WrapError(() => ElementWiseMapper.MapOver<double,double>(d,x=>DateTimeCore.UnixTimestamp(D(x))));

        [ExcelFunction(Name = "DT.FROMUNIX", Description = "Convert Unix timestamp (seconds) to Excel date serial", Category = "Date & Time")] public static object UDF_DT_FUXTS([ExcelArgument(Name = "unix_timestamp", Description = "Unix timestamp in seconds since 1970-01-01")] object ts)
            => OutputWrapper.WrapError(() => ElementWiseMapper.MapOver<double,double>(ts,x=>DateTimeCore.FromUnixTimestamp(x).ToOADate()));

        [ExcelFunction(Name = "DT.DATEDIFF", Description = "Date difference in units: 'd'=days, 'm'=months, 'y'=years, 'w'=weeks", Category = "Date & Time")] public static object UDF_DT_DDIFF([ExcelArgument(Name = "date_unit", Description = "Unit for date difference: d for days, m for months, y for years, w for weeks")] object u, [ExcelArgument(Name = "start_date", Description = "Start date as Excel serial number")] object d1, [ExcelArgument(Name = "end_date", Description = "End date as Excel serial number (required)")] object d2)
            => OutputWrapper.WrapError(() => (long)DateTimeCore.DateDiff(InputNormalizer.ToString(u),D(d1),D(d2)));

    }
}
