// <auto-generated>
//   本文件由 tools/udfgen.py 从 udf-metadata/DictSetUdf.json 生成——请勿手工修改。
//   改函数名/描述/参数/分类 → 改元数据后运行：
//       python tools/udfgen.py generate
//   改实现逻辑 → 改 Core 层，或在元数据的 expr 中调整调用。
//   元数据与生成物的一致性由 scripts/verify-udfgen.ps1 门禁强制。
// </auto-generated>
// CS8669：带 // <auto-generated> 的文件中，可空引用批注要求显式 #nullable 指令。
#nullable enable
using ExcelDna.Integration;
using ExcelFormulaLabs.Foundation;

namespace ExcelFormulaLabs.DataToolkit
{
    public static partial class DictSetUdf
    {
        [ExcelFunction(Name = "DICT.FREQUENCY", Description = "Frequency count of each unique value. Returns 2 columns: value, count", Category = "Dictionary & Set")] public static object UDF_DICT_FREQ([ExcelArgument(Name = "key_array", Description = "Array of key values")] object k)
            => OutputWrapper.WrapError(() => DictSetCore.Frequency(A(k)));

        [ExcelFunction(Name = "DICT.INTERSECT", Description = "Set intersection: values present in both arrays", Category = "Dictionary & Set")] public static object UDF_DICT_INTER([ExcelArgument(Name = "array1", Description = "First range or array")] object a, [ExcelArgument(Name = "array2", Description = "Second range or array")] object b)
            => OutputWrapper.WrapError(() => DictSetCore.Intersect(A(a),A(b)));

        [ExcelFunction(Name = "DICT.UNION", Description = "Set union: all unique values from both arrays", Category = "Dictionary & Set")] public static object UDF_DICT_UNION([ExcelArgument(Name = "array1", Description = "First range or array")] object a, [ExcelArgument(Name = "array2", Description = "Second range or array")] object b)
            => OutputWrapper.WrapError(() => DictSetCore.Union(A(a),A(b)));

        [ExcelFunction(Name = "DICT.EXCEPT", Description = "Set difference: values in first array but not in second", Category = "Dictionary & Set")] public static object UDF_DICT_EXCEPT([ExcelArgument(Name = "array1", Description = "First range or array")] object a, [ExcelArgument(Name = "array2", Description = "Second range or array")] object b)
            => OutputWrapper.WrapError(() => DictSetCore.Except(A(a),A(b)));

        [ExcelFunction(Name = "DICT.DICT", Description = "Build a 2-column dictionary from parallel key and value arrays", Category = "Dictionary & Set")] public static object UDF_DICT_DICT([ExcelArgument(Name = "key_array", Description = "Array of key values")] object k, [ExcelArgument(Name = "value_array", Description = "Array of values corresponding to each key")] object v)
            => OutputWrapper.WrapError(() => DictSetCore.Dict(A(k),A(v)));

        [ExcelFunction(Name = "DICT.COUNT", Description = "Number of rows in a 2-column dictionary table", Category = "Dictionary & Set")] public static object UDF_DICT_COUNT([ExcelArgument(Name = "dict_table", Description = "A 2-column table with keys in column 0 and values in column 1")] object d)
            => OutputWrapper.WrapError(() => (long)DictSetCore.Count(InputNormalizer.NormalizeTo2D(d)!));

        [ExcelFunction(Name = "DICT.KEYS", Description = "Extract keys (column 0) from a 2-column dictionary table", Category = "Dictionary & Set")] public static object UDF_DICT_KEYS([ExcelArgument(Name = "dict_table", Description = "A 2-column table with keys in column 0 and values in column 1")] object d)
            => OutputWrapper.WrapError(() => DictSetCore.Keys(InputNormalizer.NormalizeTo2D(d)!));

        [ExcelFunction(Name = "DICT.VALUES", Description = "Extract values (column 1) from a 2-column dictionary table", Category = "Dictionary & Set")] public static object UDF_DICT_VALS([ExcelArgument(Name = "dict_table", Description = "A 2-column table with keys in column 0 and values in column 1")] object d)
            => OutputWrapper.WrapError(() => DictSetCore.Values(InputNormalizer.NormalizeTo2D(d)!));

    }
}
