// <auto-generated>
//   本文件由 tools/udfgen.py 从 udf-metadata/JsonXmlUdf.json 生成——请勿手工修改。
//   改函数名/描述/参数/分类 → 改元数据后运行：
//       python tools/udfgen.py generate
//   改实现逻辑 → 改 Core 层，或在元数据的 expr 中调整调用。
//   元数据与生成物的一致性由 scripts/verify-udfgen.ps1 门禁强制。
// </auto-generated>
// CS8669：带 // <auto-generated> 的文件中，可空引用批注要求显式 #nullable 指令。
#nullable enable
using ExcelDna.Integration;
using ExcelFormulaLabs.Foundation;

namespace ExcelFormulaLabs.DataToolkit
{
    public static partial class JsonXmlUdf
    {
        [ExcelFunction(Name = "JSON.PARSE", Description = "Parse a JSON string into a nested table/array structure", Category = "JSON & XML")] public static object UDF_JSON_PARSE([ExcelArgument(Name = "json_text", Description = "A JSON string to parse or query")] object j)
            => OutputWrapper.WrapError(() => JsonXmlCore.JsonParse(InputNormalizer.ToString(j)));

        [ExcelFunction(Name = "JSON.QUERY", Description = "Query JSON with dot-notation path (e.g. 'store.book[0].title')", Category = "JSON & XML")] public static object UDF_JSON_QUERY([ExcelArgument(Name = "json_text", Description = "A JSON string to parse or query")] object j, [ExcelArgument(Name = "json_path", Description = "A dot-path query, e.g. store.book[0].title")] object p)
            => OutputWrapper.WrapError(() => JsonXmlCore.JsonQuery(InputNormalizer.ToString(j),InputNormalizer.ToString(p)));

        [ExcelFunction(Name = "JSON.VALIDATE", Description = "Returns TRUE if string is valid JSON", Category = "JSON & XML")] public static object UDF_JSON_VALIDATE([ExcelArgument(Name = "json_text", Description = "A JSON string to parse or query")] object j)
            => OutputWrapper.WrapError(() => JsonXmlCore.JsonValidate(InputNormalizer.ToString(j)));

        [ExcelFunction(Name = "JSON.PRETTIFY", Description = "Pretty-print JSON string with indentation", Category = "JSON & XML")] public static object UDF_JSON_PRETTIFY([ExcelArgument(Name = "json_text", Description = "A JSON string to parse or query")] object j)
            => OutputWrapper.WrapError(() => ElementWiseMapper.MapOver<string,string>(j,JsonXmlCore.JsonPrettify));

        [ExcelFunction(Name = "JSON.TOTABLE", Description = "Convert JSON array of objects to a 2D Excel table with headers", Category = "JSON & XML")] public static object UDF_JSON_TOTABLE([ExcelArgument(Name = "json_text", Description = "A JSON string to parse or query")] object j)
            => OutputWrapper.WrapError(() => (object?)JsonXmlCore.JsonToTable(InputNormalizer.ToString(j))??ExcelDna.Integration.ExcelEmpty.Value);

        [ExcelFunction(Name = "XML.XPATH", Description = "Evaluate XPath expression on XML string, returns matching element values", Category = "JSON & XML")] public static object UDF_XML_XPATH([ExcelArgument(Name = "xml_text", Description = "An XML string to parse or query")] object x, [ExcelArgument(Name = "xpath_text", Description = "An XPath expression to select XML elements")] object xp)
            => OutputWrapper.WrapError(() => JsonXmlCore.XmlXPath(InputNormalizer.ToString(x),InputNormalizer.ToString(xp)));

        [ExcelFunction(Name = "XML.VALIDATE", Description = "Returns TRUE if string is well-formed XML", Category = "JSON & XML")] public static object UDF_XML_VALIDATE([ExcelArgument(Name = "xml_text", Description = "An XML string to parse or query")] object x)
            => OutputWrapper.WrapError(() => JsonXmlCore.XmlValidate(InputNormalizer.ToString(x)));

        [ExcelFunction(Name = "XML.TOTABLE", Description = "Convert XML to a 2D Excel table using row-path XPath expression", Category = "JSON & XML")] public static object UDF_XML_TOTABLE([ExcelArgument(Name = "xml_text", Description = "An XML string to parse or query")] object x, [ExcelArgument(Name = "row_xpath", Description = "XPath that selects each row element to extract")] object rp)
            => OutputWrapper.WrapError(() => (object?)JsonXmlCore.XmlToTable(InputNormalizer.ToString(x),InputNormalizer.ToString(rp))??ExcelDna.Integration.ExcelEmpty.Value);

    }
}
