// <auto-generated>
//   本文件由 tools/udfgen.py 从 udf-metadata/PivotUdf.json 生成——请勿手工修改。
//   改函数名/描述/参数/分类 → 改元数据后运行：
//       python tools/udfgen.py generate
//   改实现逻辑 → 改 Core 层，或在元数据的 expr 中调整调用。
//   元数据与生成物的一致性由 scripts/verify-udfgen.ps1 门禁强制。
// </auto-generated>
// CS8669：带 // <auto-generated> 的文件中，可空引用批注要求显式 #nullable 指令。
#nullable enable
using ExcelDna.Integration;
using ExcelFormulaLabs.Foundation;
using System.Linq;

namespace ExcelFormulaLabs.DataToolkit
{
    public static partial class PivotUdf
    {
        [ExcelFunction(Name = "PIVOT.PIVOT", Description = "Create a pivot table. key_col=row labels, pivot_col=column labels, value_col=values, agg=sum/avg/count/min/max", Category = "Pivot")] public static object UDF_PIVOT_PIVOT([ExcelArgument(Name = "source_range", Description = "The input range or 2D array")] object d, [ExcelArgument(Name = "row_field", Description = "Column index for row labels in the pivot table")] object kc, [ExcelArgument(Name = "col_field", Description = "Column index for column labels in the pivot table")] object pc, [ExcelArgument(Name = "value_field", Description = "Column index for the values to aggregate")] object vc, [ExcelArgument(Name = "[aggregation]", Description = "Aggregation function: SUM, AVG, COUNT, MIN, or MAX (default SUM)")] object agg=null, [ExcelArgument(Name = "[has_headers]", Description = "TRUE if the first row contains column headers")] object hh=null)
            => OutputWrapper.WrapError(() => PivotCore.Pivot(InputNormalizer.NormalizeTo2D(d)!,InputNormalizer.ToInt32(kc),InputNormalizer.ToInt32(pc),InputNormalizer.ToInt32(vc),Agg(agg),InputNormalizer.ToBool(hh, true)));

        [ExcelFunction(Name = "PIVOT.UNPIVOT", Description = "Unpivot: convert wide columns to key-value rows", Category = "Pivot")] public static object UDF_PIVOT_UNPIVOT([ExcelArgument(Name = "source_range", Description = "The input range or 2D array")] object d, [ExcelArgument(Name = "id_fields", Description = "Array of column indices that identify each row in unpivot")] object ic, [ExcelArgument(Name = "value_fields", Description = "Array of column indices to unpivot into value rows")] object vc, [ExcelArgument(Name = "[has_headers]", Description = "TRUE if the first row contains column headers")] object hh=null)
            => OutputWrapper.WrapError(() => {var ids=InputNormalizer.NormalizeTo1D(ic).Select(x=>InputNormalizer.ToInt32(x)).ToArray();var vs=InputNormalizer.NormalizeTo1D(vc).Select(x=>InputNormalizer.ToInt32(x)).ToArray();return PivotCore.Unpivot(InputNormalizer.NormalizeTo2D(d)!,ids,vs,InputNormalizer.ToBool(hh, true));});

        [ExcelFunction(Name = "PIVOT.GROUPBY", Description = "Group by columns and aggregate. agg=sum/avg/count/min/max", Category = "Pivot")] public static object UDF_PIVOT_GROUPBY([ExcelArgument(Name = "source_range", Description = "The input range or 2D array")] object d, [ExcelArgument(Name = "group_fields", Description = "Array of column indices to group by")] object gc, [ExcelArgument(Name = "agg_column", Description = "Column index for aggregation")] object ac, [ExcelArgument(Name = "[aggregation]", Description = "Aggregation function: SUM, AVG, COUNT, MIN, or MAX (default SUM)")] object agg=null, [ExcelArgument(Name = "[has_headers]", Description = "TRUE if the first row contains column headers")] object hh=null)
            => OutputWrapper.WrapError(() => {var g=InputNormalizer.NormalizeTo1D(gc).Select(x=>InputNormalizer.ToInt32(x)).ToArray();return PivotCore.GroupBy(InputNormalizer.NormalizeTo2D(d)!,g,InputNormalizer.ToInt32(ac),Agg(agg),InputNormalizer.ToBool(hh, true));});

        [ExcelFunction(Name = "PIVOT.CROSSJOIN", Description = "Cross join (Cartesian product) of two tables", Category = "Pivot")] public static object UDF_PIVOT_CROSSJOIN([ExcelArgument(Name = "table1", Description = "First data range for multi-table SQL")] object a, [ExcelArgument(Name = "table2", Description = "Second data range for multi-table SQL")] object b)
            => OutputWrapper.WrapError(() => PivotCore.CrossJoin(InputNormalizer.NormalizeTo2D(a)!,InputNormalizer.NormalizeTo2D(b)!));

    }
}
