using System.Linq;
using ExcelDna.Integration;
using ExcelVbaLibraries.Foundation;

namespace ExcelVbaLibraries.DataToolkit
{
    public static class PivotUdf
    {
        [ExcelFunction(Name="PIVOT.PIVOT", Description="Create a pivot table. key_col=row labels, pivot_col=column labels, value_col=values, agg=sum/avg/count/min/max")] public static object UDF_PIVOT_PIVOT([ExcelArgument(Name="source_range", Description="The input range or 2D array")] object d, [ExcelArgument(Name="row_field", Description="Column index for row labels in the pivot table")] object kc, [ExcelArgument(Name="col_field", Description="Column index for column labels in the pivot table")] object pc, [ExcelArgument(Name="value_field", Description="Column index for the values to aggregate")] object vc, [ExcelArgument(Name="aggregation", Description="Aggregation function: SUM, AVG, COUNT, MIN, or MAX")] object agg)=>OutputWrapper.WrapError(()=>PivotCore.Pivot(InputNormalizer.NormalizeTo2D(d)!,(int)InputNormalizer.ToLong(kc),(int)InputNormalizer.ToLong(pc),(int)InputNormalizer.ToLong(vc),InputNormalizer.ToString(agg)));
        [ExcelFunction(Name="PIVOT.UNPIVOT", Description="Unpivot: convert wide columns to key-value rows")] public static object UDF_PIVOT_UNPIVOT([ExcelArgument(Name="source_range", Description="The input range or 2D array")] object d, [ExcelArgument(Name="id_fields", Description="Array of column indices that identify each row in unpivot")] object ic, [ExcelArgument(Name="value_fields", Description="Array of column indices to unpivot into value rows")] object vc)=>OutputWrapper.WrapError(()=>{var ids=InputNormalizer.NormalizeTo1D(ic).Select(x=>(int)InputNormalizer.ToLong(x)).ToArray();var vs=InputNormalizer.NormalizeTo1D(vc).Select(x=>(int)InputNormalizer.ToLong(x)).ToArray();return PivotCore.Unpivot(InputNormalizer.NormalizeTo2D(d)!,ids,vs);});
        [ExcelFunction(Name="PIVOT.GROUPBY", Description="Group by columns and aggregate. agg=sum/avg/count/min/max")] public static object UDF_PIVOT_GROUPBY([ExcelArgument(Name="source_range", Description="The input range or 2D array")] object d, [ExcelArgument(Name="group_fields", Description="Array of column indices to group by")] object gc, [ExcelArgument(Name="agg_column", Description="Column index for aggregation")] object ac, [ExcelArgument(Name="aggregation", Description="Aggregation function: SUM, AVG, COUNT, MIN, or MAX")] object agg)=>OutputWrapper.WrapError(()=>{var g=InputNormalizer.NormalizeTo1D(gc).Select(x=>(int)InputNormalizer.ToLong(x)).ToArray();return PivotCore.GroupBy(InputNormalizer.NormalizeTo2D(d)!,g,(int)InputNormalizer.ToLong(ac),InputNormalizer.ToString(agg));});
        [ExcelFunction(Name="PIVOT.CROSSJOIN", Description="Cross join (Cartesian product) of two tables")] public static object UDF_PIVOT_CROSSJOIN([ExcelArgument(Name="table1", Description="First data range for multi-table SQL")] object a, [ExcelArgument(Name="table2", Description="Second data range for multi-table SQL")] object b)=>OutputWrapper.WrapError(()=>PivotCore.CrossJoin(InputNormalizer.NormalizeTo2D(a)!,InputNormalizer.NormalizeTo2D(b)!));
    }
}
