using System;
using System.Runtime.InteropServices;
using ExcelDna.Integration;
using ExcelFormulaLabs.Foundation;

namespace ExcelFormulaLabs.DataToolkit
{
    public static class RegexUdf
    {
        // R1-4：每格 5s Timeout 在数组分发下线性放大（N 格 = N×5s CPU）。Budgeted 为
        // 一次 UDF 调用建立数组级墙钟预算（Foundation.RegexBudget）：RegexCore 每次
        // 操作取 min(单次 5s, 剩余预算)，耗尽即抛 → WrapError → #VALUE!，总耗时 ≤ 预算 + 单格。
        private static object Budgeted(Func<object> f)
        {
            using (RegexBudget.Begin()) return f();
        }

        [ExcelFunction(Name="REGEX.TEST", Description="Returns TRUE if string matches regex pattern")] public static object UDF_RX_TEST([ExcelArgument(Name="text", Description="The text string to process")] object i, [ExcelArgument(Name="pattern", Description="A regular expression pattern")] object p, [ExcelArgument(Name="[ignore_case]", Description="TRUE (default) to ignore case, FALSE for case-sensitive")] object ic=null)=>OutputWrapper.WrapError(()=>Budgeted(()=>ElementWiseMapper.MapOverMulti<string,string,bool>(i,p,(x,y)=>RegexCore.RegexTest(x,y,InputNormalizer.ToBool(ic, true)))));
        [ExcelFunction(Name="REGEX.COUNT", Description="Count of non-overlapping regex matches in a string")] public static object UDF_RX_COUNT([ExcelArgument(Name="text", Description="The text string to process")] object i, [ExcelArgument(Name="pattern", Description="A regular expression pattern")] object p, [ExcelArgument(Name="[ignore_case]", Description="TRUE (default) to ignore case, FALSE for case-sensitive")] object ic=null)=>OutputWrapper.WrapError(()=>Budgeted(()=>ElementWiseMapper.MapOverMulti<string,string,long>(i,p,(x,y)=>RegexCore.RegexCount(x,y,InputNormalizer.ToBool(ic, true)))));
        [ExcelFunction(Name="REGEX.MATCH", Description="Nth regex match substring. n=1 (default/first), n=-1 (last), or empty string if no match")] public static object UDF_RX_MATCH([ExcelArgument(Name="text", Description="The text string to process")] object i, [ExcelArgument(Name="pattern", Description="A regular expression pattern")] object p, [ExcelArgument(Name="[ignore_case]", Description="TRUE (default) to ignore case, FALSE for case-sensitive")] object ic=null, [ExcelArgument(Name="[instance_num]", Description="Which occurrence: 1=first (default), -1=last")] object n=null)=>OutputWrapper.WrapError(()=>Budgeted(()=>ElementWiseMapper.MapOverMulti<string,string,string>(i,p,(x,y)=>RegexCore.RegexMatch(x,y,InputNormalizer.ToLong(n),InputNormalizer.ToBool(ic, true)))));
        [ExcelFunction(Name="REGEX.MATCHALL", Description="All regex matches as array of strings")] public static object UDF_RX_MALL([ExcelArgument(Name="text", Description="The text string to process")] object i, [ExcelArgument(Name="pattern", Description="A regular expression pattern")] object p, [ExcelArgument(Name="[ignore_case]", Description="TRUE (default) to ignore case, FALSE for case-sensitive")] object ic=null)=>OutputWrapper.WrapError(()=>Budgeted(()=>RegexCore.RegexMatchAll(InputNormalizer.ToString(i),InputNormalizer.ToString(p),InputNormalizer.ToBool(ic, true))));
        [ExcelFunction(Name="REGEX.REPLACE", Description="Replace the nth regex match. n=0/omit=all (default), n=1=first, n=-1=last")] public static object UDF_RX_REPL([ExcelArgument(Name="text", Description="The text string to process")] object i, [ExcelArgument(Name="pattern", Description="A regular expression pattern")] object p, [ExcelArgument(Name="replacement", Description="Replacement text for regex replace")] object r, [ExcelArgument(Name="[ignore_case]", Description="TRUE (default) to ignore case, FALSE for case-sensitive")] object ic=null, [ExcelArgument(Name="[instance_num]", Description="Which occurrence: 1=first (default), -1=last")] object n=null)=>OutputWrapper.WrapError(()=>Budgeted(()=>ElementWiseMapper.MapOver<string,string>(i,s=>RegexCore.RegexReplace(s,InputNormalizer.ToString(p),InputNormalizer.ToString(r),InputNormalizer.ToLong(n),InputNormalizer.ToBool(ic, true)))));
        [ExcelFunction(Name="REGEX.SPLIT", Description="Split string by regex delimiter. n=0/omit=all splits (default), n>0=max n splits")] public static object UDF_RX_SPLIT([ExcelArgument(Name="text", Description="The text string to process")] object i, [ExcelArgument(Name="pattern", Description="A regular expression pattern")] object p, [ExcelArgument(Name="[ignore_case]", Description="TRUE (default) to ignore case, FALSE for case-sensitive")] object ic=null, [ExcelArgument(Name="[instance_num]", Description="Maximum number of splits: 0/omit=all (default), >0=max n splits")] object n=null)=>OutputWrapper.WrapError(()=>Budgeted(()=>RegexCore.RegexSplit(InputNormalizer.ToString(i),InputNormalizer.ToString(p),InputNormalizer.ToLong(n),InputNormalizer.ToBool(ic, true))));
        [ExcelFunction(Name="REGEX.GROUPS", Description="Capture groups from first match. Returns 2xn: group names row0, values row1")] public static object UDF_RX_GRP([ExcelArgument(Name="text", Description="The text string to process")] object i, [ExcelArgument(Name="pattern", Description="A regular expression pattern")] object p, [ExcelArgument(Name="[ignore_case]", Description="TRUE (default) to ignore case, FALSE for case-sensitive")] object ic=null)=>OutputWrapper.WrapError(()=>Budgeted(()=>RegexCore.RegexCaptureGroups(InputNormalizer.ToString(i),InputNormalizer.ToString(p),InputNormalizer.ToBool(ic, true))));
        [ExcelFunction(Name="REGEX.ESCAPE", Description="Escape regex special characters in a literal string")] public static object UDF_RX_ESC([ExcelArgument(Name="text", Description="The text string to process")] object l)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(l,RegexCore.RegexEscape));
        [ExcelFunction(Name="REGEX.ISMATCH", Description="Case-insensitive regex match test (alias for REGEX.TEST with ic=true)")] public static object UDF_RX_ISMATCH([ExcelArgument(Name="text", Description="The text string to process")] object i, [ExcelArgument(Name="pattern", Description="A regular expression pattern")] object p)=>OutputWrapper.WrapError(()=>Budgeted(()=>ElementWiseMapper.MapOverMulti<string,string,bool>(i,p,(x,y)=>RegexCore.RegexTest(x,y,true))));
    }
}
