using ExcelDna.Integration;
using ExcelVbaLibraries.Foundation;

namespace ExcelVbaLibraries.DataToolkit
{
    public static class RegexUdf
    {
        [ExcelFunction(Name="REGEX.TEST", Description="Returns TRUE if string matches regex pattern")] public static object UDF_RX_TEST([ExcelArgument(Name="text", Description="The text string to process")] object i, [ExcelArgument(Name="pattern", Description="A regular expression pattern")] object p, [ExcelArgument(Name="ignore_case", Description="TRUE to ignore case, FALSE or omitted for case-sensitive")] object ic)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOverMulti<string,string,bool>(i,p,(x,y)=>RegexCore.RegexTest(x,y,InputNormalizer.ToBool(ic))));
        [ExcelFunction(Name="REGEX.COUNT", Description="Count of non-overlapping regex matches in a string")] public static object UDF_RX_COUNT([ExcelArgument(Name="text", Description="The text string to process")] object i, [ExcelArgument(Name="pattern", Description="A regular expression pattern")] object p, [ExcelArgument(Name="ignore_case", Description="TRUE to ignore case, FALSE or omitted for case-sensitive")] object ic)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOverMulti<string,string,long>(i,p,(x,y)=>RegexCore.RegexCount(x,y,InputNormalizer.ToBool(ic))));
        [ExcelFunction(Name="REGEX.MATCH", Description="Nth regex match substring. n=1 (default/first), n=-1 (last), or empty string if no match")] public static object UDF_RX_MATCH([ExcelArgument(Name="text", Description="The text string to process")] object i, [ExcelArgument(Name="pattern", Description="A regular expression pattern")] object p, [ExcelArgument(Name="ignore_case", Description="TRUE to ignore case, FALSE or omitted for case-sensitive")] object ic, [ExcelArgument(Name="instance_num", Description="Which occurrence: 1=first (default), -1=last")] object n=null!)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOverMulti<string,string,string>(i,p,(x,y)=>RegexCore.RegexMatch(x,y,InputNormalizer.ToLong(n),InputNormalizer.ToBool(ic))));
        [ExcelFunction(Name="REGEX.MATCHALL", Description="All regex matches as array of strings")] public static object UDF_RX_MALL([ExcelArgument(Name="text", Description="The text string to process")] object i, [ExcelArgument(Name="pattern", Description="A regular expression pattern")] object p, [ExcelArgument(Name="ignore_case", Description="TRUE to ignore case, FALSE or omitted for case-sensitive")] object ic)=>OutputWrapper.WrapError(()=>RegexCore.RegexMatchAll(InputNormalizer.ToString(i),InputNormalizer.ToString(p),InputNormalizer.ToBool(ic)));
        [ExcelFunction(Name="REGEX.REPLACE", Description="Replace the nth regex match. n=0/omit=all (default), n=1=first, n=-1=last")] public static object UDF_RX_REPL([ExcelArgument(Name="text", Description="The text string to process")] object i, [ExcelArgument(Name="pattern", Description="A regular expression pattern")] object p, [ExcelArgument(Name="replacement", Description="Replacement text for regex replace")] object r, [ExcelArgument(Name="ignore_case", Description="TRUE to ignore case, FALSE or omitted for case-sensitive")] object ic, [ExcelArgument(Name="instance_num", Description="Which occurrence: 1=first (default), -1=last")] object n=null!)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(i,s=>RegexCore.RegexReplace(s,InputNormalizer.ToString(p),InputNormalizer.ToString(r),InputNormalizer.ToLong(n),InputNormalizer.ToBool(ic))));
        [ExcelFunction(Name="REGEX.SPLIT", Description="Split string by regex delimiter. n=0/omit=all splits (default), n>0=max n splits")] public static object UDF_RX_SPLIT([ExcelArgument(Name="text", Description="The text string to process")] object i, [ExcelArgument(Name="pattern", Description="A regular expression pattern")] object p, [ExcelArgument(Name="ignore_case", Description="TRUE to ignore case, FALSE or omitted for case-sensitive")] object ic, [ExcelArgument(Name="instance_num", Description="Which occurrence: 1=first (default), -1=last")] object n=null!)=>OutputWrapper.WrapError(()=>RegexCore.RegexSplit(InputNormalizer.ToString(i),InputNormalizer.ToString(p),InputNormalizer.ToLong(n),InputNormalizer.ToBool(ic)));
        [ExcelFunction(Name="REGEX.GROUPS", Description="Capture groups from first match. Returns 2xn: group names row0, values row1")] public static object UDF_RX_GRP([ExcelArgument(Name="text", Description="The text string to process")] object i, [ExcelArgument(Name="pattern", Description="A regular expression pattern")] object p, [ExcelArgument(Name="ignore_case", Description="TRUE to ignore case, FALSE or omitted for case-sensitive")] object ic)=>OutputWrapper.WrapError(()=>RegexCore.RegexCaptureGroups(InputNormalizer.ToString(i),InputNormalizer.ToString(p),InputNormalizer.ToBool(ic)));
        [ExcelFunction(Name="REGEX.ESCAPE", Description="Escape regex special characters in a literal string")] public static object UDF_RX_ESC([ExcelArgument(Name="text", Description="The text string to process")] object l)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(l,RegexCore.RegexEscape));
        [ExcelFunction(Name="REGEX.ISMATCH", Description="Case-insensitive regex match test (alias for REGEX.TEST with ic=true)")] public static object UDF_RX_ISMATCH([ExcelArgument(Name="text", Description="The text string to process")] object i, [ExcelArgument(Name="pattern", Description="A regular expression pattern")] object p)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOverMulti<string,string,bool>(i,p,(x,y)=>RegexCore.RegexTest(x,y,true)));
    }
}
