// <auto-generated>
//   本文件由 tools/udfgen.py 从 udf-metadata/SqlUdf.json 生成——请勿手工修改。
//   改函数名/描述/参数/分类 → 改元数据后运行：
//       python tools/udfgen.py generate
//   改实现逻辑 → 改 Core 层，或在元数据的 expr 中调整调用。
//   元数据与生成物的一致性由 scripts/verify-udfgen.ps1 门禁强制。
// </auto-generated>
// CS8669：带 // <auto-generated> 的文件中，可空引用批注要求显式 #nullable 指令。
#nullable enable
using ExcelDna.Integration;
using ExcelFormulaLabs.Foundation;
using System.Collections.Generic;

namespace ExcelFormulaLabs.DataToolkit
{
    public static partial class SqlUdf
    {
        [ExcelFunction(Name = "SQL.QUERY", Description = "Execute SQL on a range. Table = 'data'. Example: SELECT Name, SUM(Amount) FROM data GROUP BY Name", Category = "SQL")] public static object UDF_SQL_QUERY([ExcelArgument(Name = "source_range", Description = "The input range or 2D array")] object data, [ExcelArgument(Name = "sql_query", Description = "A SQL query string; table name is data")] object sql, [ExcelArgument(Name = "[has_headers]", Description = "TRUE (default): first row holds column names; FALSE: auto-generate Col1..ColN")] object hh=null)
            => OutputWrapper.WrapError(() => SqlCore.SqlQuery(InputNormalizer.NormalizeTo2D(data)!, InputNormalizer.ToString(sql), hasHeaders: InputNormalizer.ToBool(hh, true))!);

        [ExcelFunction(Name = "SQL.JOIN", Description = "SQL with 2 tables 'data' + 'extra'. Example: SELECT a.*, b.x FROM data a JOIN extra b ON a.ID=b.ID", Category = "SQL")] public static object UDF_SQL_JOIN([ExcelArgument(Name = "source_range", Description = "The input range or 2D array")] object data, [ExcelArgument(Name = "join_table", Description = "A second range to join with the data table")] object extra, [ExcelArgument(Name = "sql_query", Description = "A SQL query string; table name is data")] object sql, [ExcelArgument(Name = "[has_headers]", Description = "TRUE (default): first row holds column names; FALSE: auto-generate Col1..ColN")] object hh=null)
            => OutputWrapper.WrapError(() => { var t = new Dictionary<string, object[,]> { ["extra"] = InputNormalizer.NormalizeTo2D(extra)! }; return SqlCore.SqlQuery(InputNormalizer.NormalizeTo2D(data)!, InputNormalizer.ToString(sql), t, InputNormalizer.ToBool(hh, true))!; });

        [ExcelFunction(Name = "SQL.QUERY3", Description = "SQL with 3 tables 'data','b','c'.", Category = "SQL")] public static object UDF_SQL_QUERY3([ExcelArgument(Name = "table1", Description = "First data range for multi-table SQL")] object a, [ExcelArgument(Name = "table2", Description = "Second data range for multi-table SQL")] object b, [ExcelArgument(Name = "table3", Description = "Third data range for multi-table SQL")] object c, [ExcelArgument(Name = "sql_query", Description = "A SQL query string; table name is data")] object sql, [ExcelArgument(Name = "[has_headers]", Description = "TRUE (default): first row holds column names; FALSE: auto-generate Col1..ColN")] object hh=null)
            => OutputWrapper.WrapError(() => { var t = new Dictionary<string, object[,]> { ["b"] = InputNormalizer.NormalizeTo2D(b)!, ["c"] = InputNormalizer.NormalizeTo2D(c)! }; return SqlCore.SqlQuery(InputNormalizer.NormalizeTo2D(a)!, InputNormalizer.ToString(sql), t, InputNormalizer.ToBool(hh, true))!; });

    }
}
