using System.Linq;
using System.Runtime.InteropServices;
using ExcelDna.Integration;
using ExcelVbaLibraries.Foundation;

namespace ExcelVbaLibraries.DataToolkit
{
    public static class StringUdf
    {
        [ExcelFunction(Name="STR.REVERSE", Description="Reverse a string character-wise")] public static object UDF_STR_REV([ExcelArgument(Name="text", Description="The text string to process")] object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,StringCore.ReverseString));
        [ExcelFunction(Name="STR.NORMWS", Description="Normalize whitespace: trim and collapse multiple spaces to single")] public static object UDF_STR_NWS([ExcelArgument(Name="text", Description="The text string to process")] object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,StringCore.NormalizeWhitespace));
        [ExcelFunction(Name="STR.TITLE", Description="Convert string to title case (capitalize first letter of each word)")] public static object UDF_STR_TITLE([ExcelArgument(Name="text", Description="The text string to process")] object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,StringCore.ToTitleCase));
        [ExcelFunction(Name="STR.REMOVE", Description="Remove all occurrences of specified characters from string")] public static object UDF_STR_REM([ExcelArgument(Name="text", Description="The text string to process")] object t, [ExcelArgument(Name="old_text", Description="Characters to remove from the text")] object ch)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,s=>StringCore.RemoveChars(s,InputNormalizer.ToString(ch))));
        [ExcelFunction(Name="STR.KEEP", Description="Keep only specified characters, remove all others")] public static object UDF_STR_KEEP([ExcelArgument(Name="text", Description="The text string to process")] object t, [ExcelArgument(Name="keep_chars", Description="Characters to retain; all others are removed")] object ch)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,s=>StringCore.KeepChars(s,InputNormalizer.ToString(ch))));
        [ExcelFunction(Name="STR.PADLEFT", Description="Pad string on left to given length with pad character")] public static object UDF_STR_PADL([ExcelArgument(Name="text", Description="The text string to process")] object t, [ExcelArgument(Name="num_chars", Description="Number of characters to generate, pad, or extract")] object len, [ExcelArgument(Name="[pad_text]", Description="The padding character(s) to fill with")] object pad=null)=>OutputWrapper.WrapError(()=>{string ps=InputNormalizer.ToString(pad);char pc=ps.Length>0?ps[0]:' ';return ElementWiseMapper.MapOver<string,string>(t,s=>StringCore.PadLeft(s,(int)InputNormalizer.ToLong(len),pc));});
        [ExcelFunction(Name="STR.PADRIGHT", Description="Pad string on right to given length with pad character")] public static object UDF_STR_PADR([ExcelArgument(Name="text", Description="The text string to process")] object t, [ExcelArgument(Name="num_chars", Description="Number of characters to generate, pad, or extract")] object len, [ExcelArgument(Name="[pad_text]", Description="The padding character(s) to fill with")] object pad=null)=>OutputWrapper.WrapError(()=>{string ps=InputNormalizer.ToString(pad);char pc=ps.Length>0?ps[0]:' ';return ElementWiseMapper.MapOver<string,string>(t,s=>StringCore.PadRight(s,(int)InputNormalizer.ToLong(len),pc));});
        [ExcelFunction(Name="STR.TRUNCATE", Description="Truncate string to given length, appending suffix if truncated")] public static object UDF_STR_TRUNC([ExcelArgument(Name="text", Description="The text string to process")] object t, [ExcelArgument(Name="num_chars", Description="Number of characters to generate, pad, or extract")] object len, [ExcelArgument(Name="[suffix]", Description="Suffix to append when the text is truncated")] object sfx=null)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,s=>StringCore.Truncate(s,(int)InputNormalizer.ToLong(len),sfx==null||sfx is ExcelDna.Integration.ExcelMissing?"...":InputNormalizer.ToString(sfx))));
        [ExcelFunction(Name="STR.COUNTSUB", Description="Count occurrences of substring (case-sensitive option)")] public static object UDF_STR_CNT([ExcelArgument(Name="text", Description="The text string to process")] object t, [ExcelArgument(Name="substring", Description="Substring to search for and count")] object s, [ExcelArgument(Name="[match_case]", Description="TRUE for case-sensitive match, FALSE for case-insensitive")] object cs=null)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOverMulti<string,string,long>(t,s,(a,b)=>StringCore.CountSubstring(a,b,InputNormalizer.ToBool(cs))));
        [ExcelFunction(Name="STR.STARTSWITH", Description="Returns TRUE if string starts with prefix (case-sensitive option)")] public static object UDF_STR_SW([ExcelArgument(Name="text", Description="The text string to process")] object t, [ExcelArgument(Name="prefix", Description="Text to test at the start")] object p, [ExcelArgument(Name="[match_case]", Description="TRUE for case-sensitive match, FALSE for case-insensitive")] object cs=null)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOverMulti<string,string,bool>(t,p,(a,b)=>StringCore.StartsWithStr(a,b,InputNormalizer.ToBool(cs))));
        [ExcelFunction(Name="STR.ENDSWITH", Description="Returns TRUE if string ends with suffix (case-sensitive option)")] public static object UDF_STR_EW([ExcelArgument(Name="text", Description="The text string to process")] object t, [ExcelArgument(Name="suffix", Description="Suffix to append when the text is truncated")] object s, [ExcelArgument(Name="[match_case]", Description="TRUE for case-sensitive match, FALSE for case-insensitive")] object cs=null)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOverMulti<string,string,bool>(t,s,(a,b)=>StringCore.EndsWithStr(a,b,InputNormalizer.ToBool(cs))));
        [ExcelFunction(Name="STR.LEFTOF", Description="Extract substring left of the nth occurrence of delimiter")] public static object UDF_STR_LOF([ExcelArgument(Name="text", Description="The text string to process")] object t, [ExcelArgument(Name="delimiter", Description="The delimiter character or string")] object d, [ExcelArgument(Name="[instance_num]", Description="Which occurrence: 1=first (default), -1=last")] object n=null)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,s=>StringCore.LeftOf(s,InputNormalizer.ToString(d),InputNormalizer.ToLong(n))));
        [ExcelFunction(Name="STR.RIGHTOF", Description="Extract substring right of the nth occurrence of delimiter")] public static object UDF_STR_ROF([ExcelArgument(Name="text", Description="The text string to process")] object t, [ExcelArgument(Name="delimiter", Description="The delimiter character or string")] object d, [ExcelArgument(Name="[instance_num]", Description="Which occurrence: 1=first (default), -1=last")] object n=null)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,s=>StringCore.RightOf(s,InputNormalizer.ToString(d),InputNormalizer.ToLong(n))));
        [ExcelFunction(Name="STR.EXTRACT", Description="Extract substring between left and right delimiters (nth occurrence)")] public static object UDF_STR_EXT([ExcelArgument(Name="text", Description="The text string to process")] object t, [ExcelArgument(Name="start_delimiter", Description="The left delimiter character(s)")] object l, [ExcelArgument(Name="end_delimiter", Description="The right delimiter character(s)")] object r, [ExcelArgument(Name="[instance_num]", Description="Which occurrence: 1=first (default), -1=last")] object n=null, [ExcelArgument(Name="[include_delimiters]", Description="TRUE to include the delimiters in the result")] object inc=null)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,s=>StringCore.ExtractBetween(s,InputNormalizer.ToString(l),InputNormalizer.ToString(r),InputNormalizer.ToLong(n),InputNormalizer.ToBool(inc))));
        [ExcelFunction(Name="STR.NTHWORD", Description="Extract the nth word from a string (space-delimited)")] public static object UDF_STR_NTHW([ExcelArgument(Name="text", Description="The text string to process")] object t, [ExcelArgument(Name="[instance_num]", Description="Which occurrence: 1=first (default), -1=last")] object n=null)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,s=>StringCore.NthWord(s,InputNormalizer.ToLong(n))));
        [ExcelFunction(Name="STR.COMMONPFX", Description="Longest common prefix of two strings (case-sensitive option)")] public static object UDF_STR_CPFX([ExcelArgument(Name="text1", Description="First text string to compare")] object a, [ExcelArgument(Name="text2", Description="Second text string to compare")] object b, [ExcelArgument(Name="[match_case]", Description="TRUE for case-sensitive match, FALSE for case-insensitive")] object cs=null)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOverMulti<string,string,string>(a,b,(x,y)=>StringCore.CommonPrefix(x,y,InputNormalizer.ToBool(cs))));
        [ExcelFunction(Name="STR.TEXTJOIN", Description="Join array of values with delimiter, optionally skipping empties (like Excel TEXTJOIN)")] public static object UDF_STR_JOIN([ExcelArgument(Name="delimiter", Description="The delimiter character or string")] object d, [ExcelArgument(Name="ignore_empty", Description="TRUE to skip empty cells when joining")] object skip, [ExcelArgument(Name="text_array", Description="Array of text values to join together")] object vals)=>OutputWrapper.WrapError(()=>{var a=InputNormalizer.NormalizeTo1D(vals).Select(x=>InputNormalizer.ToString(x)).ToArray();return StringCore.TextJoin(InputNormalizer.ToString(d),InputNormalizer.ToBool(skip),a);});
        [ExcelFunction(Name="STR.LEVENSHTEIN", Description="Levenshtein edit distance between two strings")] public static object UDF_STR_LEV([ExcelArgument(Name="text1", Description="First text string to compare")] object a, [ExcelArgument(Name="text2", Description="Second text string to compare")] object b)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOverMulti<string,string,long>(a,b,(x,y)=>StringCore.LevenshteinDistance(x,y)));
        [ExcelFunction(Name="STR.SOUNDEX", Description="Soundex phonetic code of a string (4-character code)")] public static object UDF_STR_SDX([ExcelArgument(Name="text", Description="The text string to process")] object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,StringCore.Soundex));
        [ExcelFunction(Name="STR.URLENCODE", Description="URL-encode a string")] public static object UDF_STR_UENC([ExcelArgument(Name="text", Description="The text string to process")] object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,StringCore.UrlEncode));
        [ExcelFunction(Name="STR.URLDECODE", Description="URL-decode a string")] public static object UDF_STR_UDEC([ExcelArgument(Name="text", Description="The text string to process")] object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,StringCore.UrlDecode));
        [ExcelFunction(Name="STR.HTMLENCODE", Description="HTML-encode a string")] public static object UDF_STR_HENC([ExcelArgument(Name="text", Description="The text string to process")] object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,StringCore.HtmlEncode));
        [ExcelFunction(Name="STR.HTMLDECODE", Description="HTML-decode a string")] public static object UDF_STR_HDEC([ExcelArgument(Name="text", Description="The text string to process")] object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,StringCore.HtmlDecode));
        [ExcelFunction(Name="STR.BASE64ENC", Description="Base64-encode a string")] public static object UDF_STR_B64ENC([ExcelArgument(Name="text", Description="The text string to process")] object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,StringCore.Base64Encode));
        [ExcelFunction(Name="STR.BASE64DEC", Description="Base64-decode a string")] public static object UDF_STR_B64DEC([ExcelArgument(Name="text", Description="The text string to process")] object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,StringCore.Base64Decode));
        [ExcelFunction(Name="STR.UUID", Description="Generate a random UUID/GUID string")] public static object UDF_STR_UUID()=>OutputWrapper.WrapError(()=>(object)StringCore.UUID());
        [ExcelFunction(Name="STR.RNDSTR", Description="Generate random string of given length from character set")] public static object UDF_STR_RND([ExcelArgument(Name="num_chars", Description="Number of characters to generate, pad, or extract")] object len, [ExcelArgument(Name="[character_set]", Description="Characters to randomly pick from; default is A-Z, a-z, 0-9")] object cs=null)=>OutputWrapper.WrapError(()=>(object)StringCore.RandomString(InputNormalizer.ToLong(len),InputNormalizer.ToString(cs)));
        [ExcelFunction(Name="STR.RNDALPHA", Description="Generate random alphabetic string (A-Z, a-z)")] public static object UDF_STR_RNDA([ExcelArgument(Name="num_chars", Description="Number of characters to generate, pad, or extract")] object len)=>OutputWrapper.WrapError(()=>(object)StringCore.RandomString(InputNormalizer.ToLong(len),"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"));
        [ExcelFunction(Name="STR.RNDNUM", Description="Generate random numeric string (0-9 digits)")] public static object UDF_STR_RNDN([ExcelArgument(Name="num_chars", Description="Number of characters to generate, pad, or extract")] object len)=>OutputWrapper.WrapError(()=>(object)StringCore.RandomString(InputNormalizer.ToLong(len),"0123456789"));
        [ExcelFunction(Name="STR.ISNULLEMPTY", Description="Returns TRUE if string is null or empty")] public static object UDF_STR_ISNE([ExcelArgument(Name="text", Description="The text string to process")] object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,bool>(t,s=>StringCore.IsNullOrEmptyStr(s)));
        [ExcelFunction(Name="STR.ISNULLWS", Description="Returns TRUE if string is null, empty, or whitespace only")] public static object UDF_STR_ISNW([ExcelArgument(Name="text", Description="The text string to process")] object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,bool>(t,s=>StringCore.IsNullOrWhitespaceStr(s)));
        [ExcelFunction(Name="STR.COALESCE", Description="Return primary value if not null/empty, otherwise fallback value")] public static object UDF_STR_COAL([ExcelArgument(Name="value1", Description="Primary value; returned if not null or empty")] object p, [ExcelArgument(Name="value2", Description="Fallback value if the primary is null or empty")] object fb)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOverMulti<string,string,string>(p,fb,(a,b)=>StringCore.Coalesce(a,b)));
        [ExcelFunction(Name="STR.FORMAT", Description="Format a value using .NET format string (e.g. '0.00', 'yyyy-MM-dd')")] public static object UDF_STR_FMT([ExcelArgument(Name="value", Description="The value to fill or format")] object v, [ExcelArgument(Name="format_text", Description="A .NET format string, e.g. 0.00 or yyyy-MM-dd")] object fmt)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOverMulti<object,string,string>(v,fmt,(a,b)=>StringCore.FormatValue(a,b)));
        [ExcelFunction(Name="STR.STRIPHTML", Description="Strip HTML tags from a string, leaving only text content")] public static object UDF_STR_SHTML([ExcelArgument(Name="text", Description="The text string to process")] object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,StringCore.StripHtml));
    }
}
