using System.Linq;
using ExcelDna.Integration;
using ExcelVbaLibraries.Foundation;

namespace ExcelVbaLibraries.DataToolkit
{
    public static class StringUdf
    {
        [ExcelFunction(Name="STR.REVERSE", Description="Reverse a string character-wise")] public static object UDF_STR_REV(object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,StringCore.ReverseString));
        [ExcelFunction(Name="STR.NORMWS", Description="Normalize whitespace: trim and collapse multiple spaces to single")] public static object UDF_STR_NWS(object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,StringCore.NormalizeWhitespace));
        [ExcelFunction(Name="STR.TITLE", Description="Convert string to title case (capitalize first letter of each word)")] public static object UDF_STR_TITLE(object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,StringCore.ToTitleCase));
        [ExcelFunction(Name="STR.REMOVE", Description="Remove all occurrences of specified characters from string")] public static object UDF_STR_REM(object t,object ch)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,s=>StringCore.RemoveChars(s,InputNormalizer.ToString(ch))));
        [ExcelFunction(Name="STR.KEEP", Description="Keep only specified characters, remove all others")] public static object UDF_STR_KEEP(object t,object ch)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,s=>StringCore.KeepChars(s,InputNormalizer.ToString(ch))));
        [ExcelFunction(Name="STR.PADLEFT", Description="Pad string on left to given length with pad character")] public static object UDF_STR_PADL(object t,object len,object pad)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,s=>StringCore.PadLeft(s,(int)InputNormalizer.ToLong(len),InputNormalizer.ToString(pad)[0])));
        [ExcelFunction(Name="STR.PADRIGHT", Description="Pad string on right to given length with pad character")] public static object UDF_STR_PADR(object t,object len,object pad)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,s=>StringCore.PadRight(s,(int)InputNormalizer.ToLong(len),InputNormalizer.ToString(pad)[0])));
        [ExcelFunction(Name="STR.TRUNCATE", Description="Truncate string to given length, appending suffix if truncated")] public static object UDF_STR_TRUNC(object t,object len,object sfx)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,s=>StringCore.Truncate(s,(int)InputNormalizer.ToLong(len),sfx is ExcelDna.Integration.ExcelMissing?"...":InputNormalizer.ToString(sfx))));
        [ExcelFunction(Name="STR.COUNTSUB", Description="Count occurrences of substring (case-sensitive option)")] public static object UDF_STR_CNT(object t,object s,object cs)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOverMulti<string,string,long>(t,s,(a,b)=>StringCore.CountSubstring(a,b,InputNormalizer.ToBool(cs))));
        [ExcelFunction(Name="STR.STARTSWITH", Description="Returns TRUE if string starts with prefix (case-sensitive option)")] public static object UDF_STR_SW(object t,object p,object cs)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOverMulti<string,string,bool>(t,p,(a,b)=>StringCore.StartsWithStr(a,b,InputNormalizer.ToBool(cs))));
        [ExcelFunction(Name="STR.ENDSWITH", Description="Returns TRUE if string ends with suffix (case-sensitive option)")] public static object UDF_STR_EW(object t,object s,object cs)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOverMulti<string,string,bool>(t,s,(a,b)=>StringCore.EndsWithStr(a,b,InputNormalizer.ToBool(cs))));
        [ExcelFunction(Name="STR.LEFTOF", Description="Extract substring left of the nth occurrence of delimiter")] public static object UDF_STR_LOF(object t,object d,object n)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,s=>StringCore.LeftOf(s,InputNormalizer.ToString(d),InputNormalizer.ToLong(n))));
        [ExcelFunction(Name="STR.RIGHTOF", Description="Extract substring right of the nth occurrence of delimiter")] public static object UDF_STR_ROF(object t,object d,object n)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,s=>StringCore.RightOf(s,InputNormalizer.ToString(d),InputNormalizer.ToLong(n))));
        [ExcelFunction(Name="STR.EXTRACT", Description="Extract substring between left and right delimiters (nth occurrence)")] public static object UDF_STR_EXT(object t,object l,object r,object n,object inc)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,s=>StringCore.ExtractBetween(s,InputNormalizer.ToString(l),InputNormalizer.ToString(r),InputNormalizer.ToLong(n),InputNormalizer.ToBool(inc))));
        [ExcelFunction(Name="STR.NTHWORD", Description="Extract the nth word from a string (space-delimited)")] public static object UDF_STR_NTHW(object t,object n)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,s=>StringCore.NthWord(s,InputNormalizer.ToLong(n))));
        [ExcelFunction(Name="STR.COMMONPFX", Description="Longest common prefix of two strings (case-sensitive option)")] public static object UDF_STR_CPFX(object a,object b,object cs)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOverMulti<string,string,string>(a,b,(x,y)=>StringCore.CommonPrefix(x,y,InputNormalizer.ToBool(cs))));
        [ExcelFunction(Name="STR.TEXTJOIN", Description="Join array of values with delimiter, optionally skipping empties (like Excel TEXTJOIN)")] public static object UDF_STR_JOIN(object d,object skip,object vals)=>OutputWrapper.WrapError(()=>{var a=InputNormalizer.NormalizeTo1D(vals).Select(x=>InputNormalizer.ToString(x)).ToArray();return StringCore.TextJoin(InputNormalizer.ToString(d),InputNormalizer.ToBool(skip),a);});
        [ExcelFunction(Name="STR.LEVENSHTEIN", Description="Levenshtein edit distance between two strings")] public static object UDF_STR_LEV(object a,object b)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOverMulti<string,string,long>(a,b,(x,y)=>StringCore.LevenshteinDistance(x,y)));
        [ExcelFunction(Name="STR.SOUNDEX", Description="Soundex phonetic code of a string (4-character code)")] public static object UDF_STR_SDX(object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,StringCore.Soundex));
        [ExcelFunction(Name="STR.URLENCODE", Description="URL-encode a string")] public static object UDF_STR_UENC(object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,StringCore.UrlEncode));
        [ExcelFunction(Name="STR.URLDECODE", Description="URL-decode a string")] public static object UDF_STR_UDEC(object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,StringCore.UrlDecode));
        [ExcelFunction(Name="STR.HTMLENCODE", Description="HTML-encode a string")] public static object UDF_STR_HENC(object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,StringCore.HtmlEncode));
        [ExcelFunction(Name="STR.HTMLDECODE", Description="HTML-decode a string")] public static object UDF_STR_HDEC(object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,StringCore.HtmlDecode));
        [ExcelFunction(Name="STR.BASE64ENC", Description="Base64-encode a string")] public static object UDF_STR_B64ENC(object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,StringCore.Base64Encode));
        [ExcelFunction(Name="STR.BASE64DEC", Description="Base64-decode a string")] public static object UDF_STR_B64DEC(object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,StringCore.Base64Decode));
        [ExcelFunction(Name="STR.UUID", Description="Generate a random UUID/GUID string")] public static object UDF_STR_UUID()=>OutputWrapper.WrapError(()=>(object)StringCore.UUID());
        [ExcelFunction(Name="STR.RNDSTR", Description="Generate random string of given length from character set")] public static object UDF_STR_RND(object len,object cs)=>OutputWrapper.WrapError(()=>(object)StringCore.RandomString(InputNormalizer.ToLong(len),InputNormalizer.ToString(cs)));
        [ExcelFunction(Name="STR.RNDALPHA", Description="Generate random alphabetic string (A-Z, a-z)")] public static object UDF_STR_RNDA(object len)=>OutputWrapper.WrapError(()=>(object)StringCore.RandomString(InputNormalizer.ToLong(len),"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"));
        [ExcelFunction(Name="STR.RNDNUM", Description="Generate random numeric string (0-9 digits)")] public static object UDF_STR_RNDN(object len)=>OutputWrapper.WrapError(()=>(object)StringCore.RandomString(InputNormalizer.ToLong(len),"0123456789"));
        [ExcelFunction(Name="STR.ISNULLEMPTY", Description="Returns TRUE if string is null or empty")] public static object UDF_STR_ISNE(object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,bool>(t,s=>StringCore.IsNullOrEmptyStr(s)));
        [ExcelFunction(Name="STR.ISNULLWS", Description="Returns TRUE if string is null, empty, or whitespace only")] public static object UDF_STR_ISNW(object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,bool>(t,s=>StringCore.IsNullOrWhitespaceStr(s)));
        [ExcelFunction(Name="STR.COALESCE", Description="Return primary value if not null/empty, otherwise fallback value")] public static object UDF_STR_COAL(object p,object fb)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOverMulti<string,string,string>(p,fb,(a,b)=>StringCore.Coalesce(a,b)));
        [ExcelFunction(Name="STR.FORMAT", Description="Format a value using .NET format string (e.g. '0.00', 'yyyy-MM-dd')")] public static object UDF_STR_FMT(object v,object fmt)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOverMulti<string,string,string>(v,fmt,(a,b)=>string.Format(b.Contains('{')||b.Contains('}')?"{0}":$"{{0:{b}}}",a)));
        [ExcelFunction(Name="STR.STRIPHTML", Description="Strip HTML tags from a string, leaving only text content")] public static object UDF_STR_SHTML(object t)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,string>(t,s=>System.Text.RegularExpressions.Regex.Replace(s,"<[^>]+>","",System.Text.RegularExpressions.RegexOptions.None,System.TimeSpan.FromSeconds(5))));
    }
}
