// <auto-generated>
//   本文件由 tools/udfgen.py 从 udf-metadata/DoeAnalysisUdf.json 生成——请勿手工修改。
//   改函数名/描述/参数/分类 → 改元数据后运行：
//       python tools/udfgen.py generate
//   改实现逻辑 → 改 Core 层，或在元数据的 expr 中调整调用。
//   元数据与生成物的一致性由 scripts/verify-udfgen.ps1 门禁强制。
// </auto-generated>
// CS8669：带 // <auto-generated> 的文件中，可空引用批注要求显式 #nullable 指令。
#nullable enable
using ExcelDna.Integration;
using ExcelFormulaLabs.Foundation;

namespace ExcelFormulaLabs.Analytics
{
    public static partial class DoeAnalysisUdf
    {
        [ExcelFunction(Name = "DOE.ANALYZE", Description = "DOE effect table (term, coef, effect, t, p) from a coded design matrix and response.", Category = "DOE")] public static object UDF_DOE_ANALYZE([ExcelArgument(Name = "design", Description = "Coded factor matrix (DOE.PLAN factor columns)")] object design, [ExcelArgument(Name = "response", Description = "Response column (one value per run)")] object response, [ExcelArgument(Name = "[terms]", Description = "Terms: \"main\", \"2way\" (default), or \"quadratic\"")] object terms=null)
            => OutputWrapper.WrapError(() => { double[,] X = M(design); double[] y = V(response); var (maxOrder, quadratic) = EffectiveTerms(X, terms); return DoeAnalysisCore.Analyze(X, y, maxOrder, quadratic); });

        [ExcelFunction(Name = "DOE.ANOVA", Description = "Multi-factor ANOVA table (SS, df, MS, F, p per term) from a coded design matrix and response.", Category = "DOE")] public static object UDF_DOE_ANOVA([ExcelArgument(Name = "design", Description = "Coded factor matrix (DOE.PLAN factor columns)")] object design, [ExcelArgument(Name = "response", Description = "Response column (one value per run)")] object response, [ExcelArgument(Name = "[terms]", Description = "Terms: \"main\", \"2way\" (default), or \"quadratic\"")] object terms=null)
            => OutputWrapper.WrapError(() => { double[,] X = M(design); double[] y = V(response); var (maxOrder, quadratic) = EffectiveTerms(X, terms); return DoeAnalysisCore.Anova(X, y, maxOrder, quadratic); });

        [ExcelFunction(Name = "DOE.PARETO", Description = "DOE Pareto ranking of effects (term, effect) sorted by descending magnitude.", Category = "DOE")] public static object UDF_DOE_PARETO([ExcelArgument(Name = "design", Description = "Coded factor matrix (DOE.PLAN factor columns)")] object design, [ExcelArgument(Name = "response", Description = "Response column (one value per run)")] object response, [ExcelArgument(Name = "[terms]", Description = "Terms: \"main\", \"2way\" (default), or \"quadratic\"")] object terms=null)
            => OutputWrapper.WrapError(() => { double[,] X = M(design); double[] y = V(response); var (maxOrder, quadratic) = EffectiveTerms(X, terms); return DoeAnalysisCore.Pareto(X, y, maxOrder, quadratic); });

    }
}
