// <auto-generated>
//   本文件由 tools/udfgen.py 从 udf-metadata/DoeUdf.json 生成——请勿手工修改。
//   改函数名/描述/参数/分类 → 改元数据后运行：
//       python tools/udfgen.py generate
//   改实现逻辑 → 改 Core 层，或在元数据的 expr 中调整调用。
//   元数据与生成物的一致性由 scripts/verify-udfgen.ps1 门禁强制。
// </auto-generated>
// CS8669：带 // <auto-generated> 的文件中，可空引用批注要求显式 #nullable 指令。
#nullable enable
using ExcelDna.Integration;
using ExcelFormulaLabs.Foundation;

namespace ExcelFormulaLabs.Analytics
{
    public static partial class DoeUdf
    {
        [ExcelFunction(Name = "DOE.PLAN", Description = "Generate a DOE design matrix (full/taguchi/fractional/rsm/bb); StdOrder + RunOrder + coded factors.", Category = "DOE")] public static object UDF_DOE_PLAN([ExcelArgument(Name = "factor_qty1", Description = "Number of factors in group 1")] object qty1, [ExcelArgument(Name = "factor_level1", Description = "Levels per factor in group 1")] object level1, [ExcelArgument(Name = "factor_qty2", Description = "Number of factors in group 2")] object qty2, [ExcelArgument(Name = "factor_level2", Description = "Levels per factor in group 2")] object level2, [ExcelArgument(Name = "method", Description = "Design method: FULL, TAGUCHI, FRACTIONAL, RSM, or BB")] object method, [ExcelArgument(Name = "[randomize]", Description = "Randomize run order (default TRUE)")] object randomize=null, [ExcelArgument(Name = "[seed]", Description = "Fixed seed for reproducible run order")] object seed=null)
            => OutputWrapper.WrapError(() => DoeCore.Plan( InputNormalizer.ToInt32(qty1), InputNormalizer.ToInt32(level1), InputNormalizer.ToInt32(qty2), InputNormalizer.ToInt32(level2), InputNormalizer.ToString(method), InputNormalizer.ToBool(randomize, true), InputNormalizer.IsOmitted(seed) ? (long?)null : InputNormalizer.ToLong(seed)));

    }
}
