// <auto-generated>
//   本文件由 tools/udfgen.py 从 udf-metadata/LinalgUdf.json 生成——请勿手工修改。
//   改函数名/描述/参数/分类 → 改元数据后运行：
//       python tools/udfgen.py generate
//   改实现逻辑 → 改 Core 层，或在元数据的 expr 中调整调用。
//   元数据与生成物的一致性由 scripts/verify-udfgen.ps1 门禁强制。
// </auto-generated>
// CS8669：带 // <auto-generated> 的文件中，可空引用批注要求显式 #nullable 指令。
#nullable enable
using ExcelDna.Integration;
using ExcelFormulaLabs.Foundation;

namespace ExcelFormulaLabs.Analytics
{
    public static partial class LinalgUdf
    {
        [ExcelFunction(Name = "LINALG.SVD_U", Description = "SVD left singular vectors (U matrix). A = U*diag(S)*Vt.", Category = "Linear Algebra")] public static object UDF_LINALG_SVD_U([ExcelArgument(Name = "array", Description = "A range or 2D array")] object d)
            => OutputWrapper.WrapError(() => LinalgCore.SvdU(M(d)));

        [ExcelFunction(Name = "LINALG.SVD_S", Description = "SVD singular values (S vector). Sorted descending.", Category = "Linear Algebra")] public static object UDF_LINALG_SVD_S([ExcelArgument(Name = "array", Description = "A range or 2D array")] object d)
            => OutputWrapper.WrapError(() => LinalgCore.SvdS(M(d)));

        [ExcelFunction(Name = "LINALG.SVD_VT", Description = "SVD right singular vectors transposed (Vt matrix). A = U*diag(S)*Vt.", Category = "Linear Algebra")] public static object UDF_LINALG_SVD_VT([ExcelArgument(Name = "array", Description = "A range or 2D array")] object d)
            => OutputWrapper.WrapError(() => LinalgCore.SvdVt(M(d)));

        [ExcelFunction(Name = "LINALG.QR_Q", Description = "QR decomposition orthogonal matrix Q. A = Q*R.", Category = "Linear Algebra")] public static object UDF_LINALG_QR_Q([ExcelArgument(Name = "array", Description = "A range or 2D array")] object d)
            => OutputWrapper.WrapError(() => LinalgCore.QrQ(M(d)));

        [ExcelFunction(Name = "LINALG.QR_R", Description = "QR decomposition upper-triangular matrix R. A = Q*R.", Category = "Linear Algebra")] public static object UDF_LINALG_QR_R([ExcelArgument(Name = "array", Description = "A range or 2D array")] object d)
            => OutputWrapper.WrapError(() => LinalgCore.QrR(M(d)));

        [ExcelFunction(Name = "LINALG.LU_L", Description = "LU decomposition lower-triangular matrix L. A = P*L*U.", Category = "Linear Algebra")] public static object UDF_LINALG_LU_L([ExcelArgument(Name = "array", Description = "A range or 2D array")] object d)
            => OutputWrapper.WrapError(() => LinalgCore.LuL(M(d)));

        [ExcelFunction(Name = "LINALG.LU_U", Description = "LU decomposition upper-triangular matrix U. A = P*L*U.", Category = "Linear Algebra")] public static object UDF_LINALG_LU_U([ExcelArgument(Name = "array", Description = "A range or 2D array")] object d)
            => OutputWrapper.WrapError(() => LinalgCore.LuU(M(d)));

        [ExcelFunction(Name = "LINALG.LU_P", Description = "LU decomposition permutation matrix P. A = P*L*U.", Category = "Linear Algebra")] public static object UDF_LINALG_LU_P([ExcelArgument(Name = "array", Description = "A range or 2D array")] object d)
            => OutputWrapper.WrapError(() => LinalgCore.LuP(M(d)));

        [ExcelFunction(Name = "LINALG.PINV", Description = "Moore-Penrose pseudo-inverse.", Category = "Linear Algebra")] public static object UDF_LINALG_PINV([ExcelArgument(Name = "array", Description = "A range or 2D array")] object d)
            => OutputWrapper.WrapError(() => LinalgCore.PseudoInverse(M(d)));

        [ExcelFunction(Name = "LINALG.DET", Description = "Determinant.", Category = "Linear Algebra")] public static object UDF_LINALG_DET([ExcelArgument(Name = "array", Description = "A range or 2D array")] object d)
            => OutputWrapper.WrapError(() => LinalgCore.Determinant(M(d)));

        [ExcelFunction(Name = "LINALG.SOLVE", Description = "Solve Ax=b.", Category = "Linear Algebra")] public static object UDF_LINALG_SOLVE([ExcelArgument(Name = "array1", Description = "First range or array")] object A, [ExcelArgument(Name = "array2", Description = "Second range or array")] object b)
            => OutputWrapper.WrapError(() => LinalgCore.Solve(M(A), V(b)));

        [ExcelFunction(Name = "LINALG.CHOLESKY", Description = "Cholesky decomposition.", Category = "Linear Algebra")] public static object UDF_LINALG_CHOLESKY([ExcelArgument(Name = "array", Description = "A range or 2D array")] object d)
            => OutputWrapper.WrapError(() => LinalgCore.Cholesky(M(d)));

        [ExcelFunction(Name = "LINALG.EIGEN", Description = "Eigenvalues.", Category = "Linear Algebra")] public static object UDF_LINALG_EIGEN([ExcelArgument(Name = "array", Description = "A range or 2D array")] object d)
            => OutputWrapper.WrapError(() => LinalgCore.Eigenvalues(M(d)));

        [ExcelFunction(Name = "LINALG.COND", Description = "Condition number.", Category = "Linear Algebra")] public static object UDF_LINALG_COND([ExcelArgument(Name = "array", Description = "A range or 2D array")] object d)
            => OutputWrapper.WrapError(() => LinalgCore.ConditionNumber(M(d)));

        [ExcelFunction(Name = "LINALG.RANK", Description = "Numerical rank. Tolerance = absolute singular-value threshold; default 0 = relative (numpy convention).", Category = "Linear Algebra")] public static object UDF_LINALG_RANK([ExcelArgument(Name = "array", Description = "A range or 2D array")] object d, [ExcelArgument(Name = "[tolerance]", Description = "Tolerance threshold for numerical rank detection; default 0 = relative (max_sv * max(rows,cols) * 1e-16)")] object tol=null)
            => OutputWrapper.WrapError(() => (long)LinalgCore.Rank(M(d), tol==null||tol is ExcelDna.Integration.ExcelMissing?0:InputNormalizer.ToDouble(tol)));

        [ExcelFunction(Name = "LINALG.IDENTITY", Description = "Identity matrix.", Category = "Linear Algebra")] public static object UDF_LINALG_IDENTITY([ExcelArgument(Name = "size", Description = "The matrix dimension, e.g. 3 for a 3x3 identity matrix")] object n)
            => OutputWrapper.WrapError(() => LinalgCore.Identity(InputNormalizer.ToInt32(n)));

        [ExcelFunction(Name = "LINALG.MATMUL", Description = "Matrix multiplication.", Category = "Linear Algebra")] public static object UDF_LINALG_MATMUL([ExcelArgument(Name = "array1", Description = "First range or array")] object A, [ExcelArgument(Name = "array2", Description = "Second range or array")] object B)
            => OutputWrapper.WrapError(() => LinalgCore.MatMul(M(A), M(B)));

        [ExcelFunction(Name = "LINALG.TRANSPOSE", Description = "Transpose.", Category = "Linear Algebra")] public static object UDF_LINALG_TRANSPOSE([ExcelArgument(Name = "array", Description = "A range or 2D array")] object d)
            => OutputWrapper.WrapError(() => LinalgCore.Transpose(M(d)));

        [ExcelFunction(Name = "LINALG.TRACE", Description = "Trace.", Category = "Linear Algebra")] public static object UDF_LINALG_TRACE([ExcelArgument(Name = "array", Description = "A range or 2D array")] object d)
            => OutputWrapper.WrapError(() => LinalgCore.Trace(M(d)));

    }
}
