using ExcelDna.Integration;
using ExcelVbaLibraries.Foundation;

namespace ExcelVbaLibraries.Analytics
{
    public static class PhyChemUdf
    {
        [ExcelFunction(Name="PHYCHEM.MOLWT", Description="Molecular weight from chemical formula (e.g. 'H2SO4')")] public static object UDF_PC_MOLWT([ExcelArgument(Name="formula_text", Description="A chemical formula, e.g. H2SO4 or Fe4[Fe(CN)6]3")] object f)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<string,double>(f,PhyChemCore.MolecularWeight));
        [ExcelFunction(Name="PHYCHEM.TEMP", Description="Convert temperature between units: C, F, K")] public static object UDF_PC_TEMP([ExcelArgument(Name="number", Description="A numeric value or array of numbers")] object v, [ExcelArgument(Name="from_unit", Description="Source unit abbreviation, e.g. C, ATM, KG, L")] object from, [ExcelArgument(Name="to_unit", Description="Target unit abbreviation, e.g. F, PSI, LB, GAL")] object to){ var f=S(from);var t=S(to);return OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<double,double>(v,d=>PhyChemCore.ConvertTemperature(d,f,t))); }
        [ExcelFunction(Name="PHYCHEM.PRESS", Description="Convert pressure between units: ATM, PSI, PA, KPA, BAR, MMHG, TORR")] public static object UDF_PC_PRESS([ExcelArgument(Name="number", Description="A numeric value or array of numbers")] object v, [ExcelArgument(Name="from_unit", Description="Source unit abbreviation, e.g. C, ATM, KG, L")] object from, [ExcelArgument(Name="to_unit", Description="Target unit abbreviation, e.g. F, PSI, LB, GAL")] object to){ var f=S(from);var t=S(to);return OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<double,double>(v,d=>PhyChemCore.ConvertPressure(d,f,t))); }
        [ExcelFunction(Name="PHYCHEM.VOL", Description="Convert volume between units: L, ML, M3, GAL, QT, FT3")] public static object UDF_PC_VOL([ExcelArgument(Name="number", Description="A numeric value or array of numbers")] object v, [ExcelArgument(Name="from_unit", Description="Source unit abbreviation, e.g. C, ATM, KG, L")] object from, [ExcelArgument(Name="to_unit", Description="Target unit abbreviation, e.g. F, PSI, LB, GAL")] object to){ var f=S(from);var t=S(to);return OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<double,double>(v,d=>PhyChemCore.ConvertVolume(d,f,t))); }
        [ExcelFunction(Name="PHYCHEM.MASS", Description="Convert mass between units: KG, G, MG, LB, OZ, TON")] public static object UDF_PC_MASS([ExcelArgument(Name="number", Description="A numeric value or array of numbers")] object v, [ExcelArgument(Name="from_unit", Description="Source unit abbreviation, e.g. C, ATM, KG, L")] object from, [ExcelArgument(Name="to_unit", Description="Target unit abbreviation, e.g. F, PSI, LB, GAL")] object to){ var f=S(from);var t=S(to);return OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<double,double>(v,d=>PhyChemCore.ConvertMass(d,f,t))); }
        [ExcelFunction(Name="PHYCHEM.C_TO_F", Description="Celsius to Fahrenheit")] public static object UDF_PC_CTOF([ExcelArgument(Name="celsius", Description="Temperature in degrees Celsius")] object v)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<double,double>(v,d=>PhyChemCore.ConvertTemperature(d,"C","F")));
        [ExcelFunction(Name="PHYCHEM.F_TO_C", Description="Fahrenheit to Celsius")] public static object UDF_PC_FTOC([ExcelArgument(Name="fahrenheit", Description="Temperature in degrees Fahrenheit")] object v)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<double,double>(v,d=>PhyChemCore.ConvertTemperature(d,"F","C")));
        [ExcelFunction(Name="PHYCHEM.KG_TO_LB", Description="Kilograms to pounds")] public static object UDF_PC_KG2LB([ExcelArgument(Name="kg", Description="Mass in kilograms")] object v)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<double,double>(v,d=>PhyChemCore.ConvertMass(d,"KG","LB")));
        [ExcelFunction(Name="PHYCHEM.LB_TO_KG", Description="Pounds to kilograms")] public static object UDF_PC_LB2KG([ExcelArgument(Name="lb", Description="Mass in pounds")] object v)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<double,double>(v,d=>PhyChemCore.ConvertMass(d,"LB","KG")));
        [ExcelFunction(Name="PHYCHEM.L_TO_GAL", Description="Liters to US gallons")] public static object UDF_PC_L2GAL([ExcelArgument(Name="liters", Description="Volume in liters")] object v)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<double,double>(v,d=>PhyChemCore.ConvertVolume(d,"L","GAL")));
        [ExcelFunction(Name="PHYCHEM.GAL_TO_L", Description="US gallons to liters")] public static object UDF_PC_GAL2L([ExcelArgument(Name="gallons", Description="Volume in US gallons")] object v)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<double,double>(v,d=>PhyChemCore.ConvertVolume(d,"GAL","L")));
        [ExcelFunction(Name="PHYCHEM.ATM_TO_PSI", Description="Atmospheres to PSI")] public static object UDF_PC_ATM2PSI([ExcelArgument(Name="atm", Description="Pressure in atmospheres")] object v)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<double,double>(v,d=>PhyChemCore.ConvertPressure(d,"ATM","PSI")));
        [ExcelFunction(Name="PHYCHEM.PSI_TO_ATM", Description="PSI to atmospheres")] public static object UDF_PC_PSI2ATM([ExcelArgument(Name="psi", Description="Pressure in pounds per square inch")] object v)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOver<double,double>(v,d=>PhyChemCore.ConvertPressure(d,"PSI","ATM")));
        [ExcelFunction(Name="PHYCHEM.IDEALGAS", Description="Ideal gas law: PV = nRT. Solve for any unknown (pass * for variable to solve)")] public static object UDF_PC_GAS([ExcelArgument(Name="pressure", Description="Pressure (P) in the ideal gas law PV=nRT")] object p, [ExcelArgument(Name="volume", Description="Volume (V) in ideal gas law or gas volume to convert")] object v, [ExcelArgument(Name="moles", Description="Number of moles (n) in the ideal gas law PV=nRT")] object n, [ExcelArgument(Name="temperature", Description="Temperature (T) in Kelvin for ideal gas law")] object t)=>OutputWrapper.WrapError(()=>PhyChemCore.IdealGasLaw(V(p),V(v),V(n),V(t)));
        [ExcelFunction(Name="PHYCHEM.GASSTP", Description="Convert gas volume to standard temperature and pressure (STP)")] public static object UDF_PC_STP([ExcelArgument(Name="volume", Description="Volume (V) in ideal gas law or gas volume to convert")] object vol, [ExcelArgument(Name="temperature", Description="Temperature (T) in Kelvin for ideal gas law")] object temp, [ExcelArgument(Name="pressure", Description="Pressure (P) in the ideal gas law PV=nRT")] object press)=>OutputWrapper.WrapError(()=>PhyChemCore.GasToSTP(InputNormalizer.ToDouble(vol),InputNormalizer.ToDouble(temp),InputNormalizer.ToDouble(press)));
        [ExcelFunction(Name="PHYCHEM.DENSITY", Description="Compute density: mass / volume")] public static object UDF_PC_DEN([ExcelArgument(Name="mass", Description="Mass value for density calculation")] object mass, [ExcelArgument(Name="volume", Description="Volume (V) in ideal gas law or gas volume to convert")] object vol)=>OutputWrapper.WrapError(()=>ElementWiseMapper.MapOverMulti<double,double,double>(mass,vol,(m,v)=>v==0?double.NaN:m/v)); // L2 zero-denominator guard
        private static string S(object o)=>InputNormalizer.ToString(o);
        // Checks both Foundation.ExcelEmpty and ExcelDna.Integration.ExcelEmpty.
        // Foundation's InputNormalizer only handles its own ExcelEmpty; Excel-DNA's
        // ExcelEmpty (empty cells from ranges) requires a separate guard here.
        private static double? V(object o){if(o is Foundation.ExcelEmpty||o is ExcelDna.Integration.ExcelEmpty||o==null||o is string s&&s=="*")return null;var d=InputNormalizer.ToDouble(o);return double.IsNaN(d)?null:d;}
    }
}
