// <auto-generated>
//   本文件由 tools/udfgen.py 从 udf-metadata/RegressionUdf.json 生成——请勿手工修改。
//   改函数名/描述/参数/分类 → 改元数据后运行：
//       python tools/udfgen.py generate
//   改实现逻辑 → 改 Core 层，或在元数据的 expr 中调整调用。
//   元数据与生成物的一致性由 scripts/verify-udfgen.ps1 门禁强制。
// </auto-generated>
// CS8669：带 // <auto-generated> 的文件中，可空引用批注要求显式 #nullable 指令。
#nullable enable
using ExcelDna.Integration;
using ExcelFormulaLabs.Foundation;
using System.Linq;

namespace ExcelFormulaLabs.Analytics
{
    public static partial class RegressionUdf
    {
        [ExcelFunction(Name = "REGRESS.OLS", Description = "OLS regression; returns an 11-row report table (coefficients, fit, inference).", Category = "Regression")] public static object UDF_REGRESS_OLS([ExcelArgument(Name = "known_y", Description = "The Y variable range (dependent variable)")] object y, [ExcelArgument(Name = "known_x", Description = "The X variable range (independent variables)")] object X)
            => OutputWrapper.WrapError(() => AnalyticsHelpers.DictToReport(RegressionCore.FitOLS(M(X), V(y))));

        [ExcelFunction(Name = "REGRESS.WLS", Description = "Weighted Least Squares for heteroskedastic data; same 11-row report as OLS.", Category = "Regression")] public static object UDF_REGRESS_WLS([ExcelArgument(Name = "known_y", Description = "The Y variable range (dependent variable)")] object y, [ExcelArgument(Name = "known_x", Description = "The X variable range (independent variables)")] object X, [ExcelArgument(Name = "weights", Description = "Weight values for weighted least squares")] object w)
            => OutputWrapper.WrapError(() => AnalyticsHelpers.DictToReport(RegressionCore.FitWLS(M(X), V(y), V(w))));

        [ExcelFunction(Name = "REGRESS.RIDGE", Description = "Ridge regression (L2, default lambda=1.0); no se/t/p (inference invalid).", Category = "Regression")] public static object UDF_REGRESS_RIDGE([ExcelArgument(Name = "known_y", Description = "The Y variable range (dependent variable)")] object y, [ExcelArgument(Name = "known_x", Description = "The X variable range (independent variables)")] object X, [ExcelArgument(Name = "[lambda]", Description = "Regularization parameter; default is 1.0")] object lambda=null)
            => OutputWrapper.WrapError(() => AnalyticsHelpers.DictToReport(RegressionCore.FitRidge(M(X), V(y), InputNormalizer.IsOmitted(lambda)?1.0:InputNormalizer.ToDouble(lambda))));

        [ExcelFunction(Name = "REGRESS.ANOVA1", Description = "One-way ANOVA (groups as columns); returns SS, df, MS, F and p-value report.", Category = "Regression")] public static object UDF_REGRESS_ANOVA1([ExcelArgument(Name = "input_range", Description = "Input data range with groups as columns")] object data)
            => OutputWrapper.WrapError(() => AnalyticsHelpers.DictToReport(RegressionCore.AnovaOneWay(AnalyticsHelpers.ToJaggedColumns(data))));

        [ExcelFunction(Name = "REGRESS.FACTORIMP", Description = "Rank predictor importance by |t| from standardized OLS (0-based columns).", Category = "Regression")] public static object UDF_REGRESS_FACTORIMP([ExcelArgument(Name = "known_y", Description = "The Y variable range (dependent variable)")] object y, [ExcelArgument(Name = "known_x", Description = "The X variable range (independent variables)")] object X)
            => OutputWrapper.WrapError(() => RegressionCore.FactorImportance(M(X), V(y)).Select(i=>(double)i).ToArray());

        [ExcelFunction(Name = "REGRESS.COEF", Description = "OLS regression coefficients only (beta vector).", Category = "Regression")] public static object UDF_REGRESS_COEF([ExcelArgument(Name = "known_y", Description = "The Y variable range (dependent variable)")] object y, [ExcelArgument(Name = "known_x", Description = "The X variable range (independent variables)")] object X)
            => OutputWrapper.WrapError(() => (double[])RegressionCore.FitOLS(M(X), V(y))["coefficients"]);

        [ExcelFunction(Name = "REGRESS.RSQ", Description = "OLS R-squared (coefficient of determination). 0-1; 1 = perfect fit.", Category = "Regression")] public static object UDF_REGRESS_RSQ([ExcelArgument(Name = "known_y", Description = "The Y variable range (dependent variable)")] object y, [ExcelArgument(Name = "known_x", Description = "The X variable range (independent variables)")] object X)
            => OutputWrapper.WrapError(() => (double)RegressionCore.FitOLS(M(X), V(y))["r_squared"]);

    }
}
