// <auto-generated>
//   本文件由 tools/udfgen.py 从 udf-metadata/SolveUdf.json 生成——请勿手工修改。
//   改函数名/描述/参数/分类 → 改元数据后运行：
//       python tools/udfgen.py generate
//   改实现逻辑 → 改 Core 层，或在元数据的 expr 中调整调用。
//   元数据与生成物的一致性由 scripts/verify-udfgen.ps1 门禁强制。
// </auto-generated>
// CS8669：带 // <auto-generated> 的文件中，可空引用批注要求显式 #nullable 指令。
#nullable enable
using ExcelDna.Integration;
using ExcelFormulaLabs.Foundation;
using System;

namespace ExcelFormulaLabs.Analytics
{
    public static partial class SolveUdf
    {
        [ExcelFunction(Name = "SOLVE.INVERSE", Description = "Invert process settings to hit output targets; returns a recommendation table.", Category = "Solve")] public static object UDF_SOLVE_INVERSE([ExcelArgument(Name = "data", Description = "History table with headers; may include request rows with blank adjustable columns. SharedOutput* columns pool one shared rate.")] object data, [ExcelArgument(Name = "[request]", Description = "Optional separate request table with the same headers; data is then pure history.")] object request=null, [ExcelArgument(Name = "[bounds]", Description = "Optional bounds table (variable name or index, lower, upper); defaults to history min/max.")] object bounds=null, [ExcelArgument(Name = "[model]", Description = "Model: auto (default), linear, poly, rate or rate_poly.")] object model=null, [ExcelArgument(Name = "[seed]", Description = "Random seed for optimizer and sampling; default 42.")] object seed=null, [ExcelArgument(Name = "[max_starts]", Description = "Number of optimization starts (1-50); default 10.")] object maxStarts=null)
            => OutputWrapper.WrapError(() => SolveCore.Inverse( RequiredTable(data, "data"), OptionalTable(request), OptionalTable(bounds), InputNormalizer.ToString(model), InputNormalizer.IsOmitted(seed) ? 42L : InputNormalizer.ToLong(seed), InputNormalizer.IsOmitted(maxStarts) ? 10 : InputNormalizer.ToInt32(maxStarts)));

        [ExcelFunction(Name = "SOLVE.PREDICT", Description = "Forward-predict outputs for one or more complete parameter rows.", Category = "Solve")] public static object UDF_SOLVE_PREDICT([ExcelArgument(Name = "data", Description = "History table with headers.")] object data, [ExcelArgument(Name = "values", Description = "One or more rows of non-output values (Incoming + Variable + Fixed, data order).")] object values, [ExcelArgument(Name = "[model]", Description = "Model: auto (default), linear, poly, rate or rate_poly.")] object model=null)
            => OutputWrapper.WrapError(() => SolveCore.PredictTable( RequiredTable(data, "data"), RequiredTable(values, "values"), InputNormalizer.ToString(model)));

        [ExcelFunction(Name = "SOLVE.QUALITY", Description = "Cross-validated model quality per output (R2 / MAE by candidate model).", Category = "Solve")] public static object UDF_SOLVE_QUALITY([ExcelArgument(Name = "data", Description = "History table with headers.")] object data, [ExcelArgument(Name = "[model]", Description = "Model: auto (default), linear, poly, rate or rate_poly.")] object model=null, [ExcelArgument(Name = "[seed]", Description = "Random seed for fold shuffling; default 42.")] object seed=null)
            => OutputWrapper.WrapError(() => SolveCore.Quality( RequiredTable(data, "data"), InputNormalizer.ToString(model), InputNormalizer.IsOmitted(seed) ? 42L : InputNormalizer.ToLong(seed)));

        [ExcelFunction(Name = "SOLVE.EQUATION", Description = "Forward equation plus closed-form inverse formula for single-variable linear models.", Category = "Solve")] public static object UDF_SOLVE_EQUATION([ExcelArgument(Name = "data", Description = "History table with headers.")] object data, [ExcelArgument(Name = "[model]", Description = "Model: auto (default), linear, poly, rate or rate_poly.")] object model=null)
            => OutputWrapper.WrapError(() => SolveCore.Equation( RequiredTable(data, "data"), InputNormalizer.ToString(model)));

    }
}
